### ISSUE TITLE
Templates TODO

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#1199]
Here is a TODO for generics:

* [x] The operator overloading (+, *, - /):
  * [x] change `instantiate array_tmpl(integer, add_integer, zero_integer), only: mysum_integer => mysum_t` to `instantiate array_tmpl(integer, operator(+), zero_integer), only: mysum_integer => mysum_t`
    * [x] support user defined `operator(+)` (https://github.com/lfortran/lfortran/pull/1268)
    * [x] implicitly create the operator function implementations based on just specifying `operator(+)`
  * [x] a separate feature is to generate renaming in the template body, change `r = plus_t(r, a(i))` to `r = r + a(i)`, by using standard Fortran generic renaming, to identify `operator(+)` with the implementation `plus_t`.
* [x] Improve the error message in https://github.com/lfortran/lfortran/pull/1168 (fixed in https://github.com/lfortran/lfortran/pull/1215)
* [x] unify `instantiate_Function`
* [x] in general moving template related ASR code from the frontend into libasr, and make sure exactly the same code works for both LPython and LFortran
* [ ] robustness / hardening (more tests and combination of types / arrays)
* [x] Get the generic matrix example working: https://github.com/j3-fortran/generics/tree/7ba5a5b1f24dc4d9c200c7a1e922c0ef4ce80860/examples/linear_algebra
* [x] Investigate if it is possible to "compose" requirements (so that the user can reuse existing requirements and compose them in a new template)
* [x] Update the syntax to the latest proposals (`type :: T; end type` changed)
* [ ] Review the existing proposals for Fortran and see if there are any other features missing (besides "any rank")
* [ ] any rank arrays: https://github.com/lfortran/lfortran/issues/1422

**Comment by certik** [comment]
Rank is known, examples:
```fortran
subroutine f(x)
integer, intent(in) :: x(:)
end subroutine

subroutine f(n, x)
integer, intent(in) :: n, x(n)
end subroutine

subroutine f(x)
integer, intent(in) :: x(:,:)
end subroutine

subroutine f(n, m, x)
integer, intent(in) :: n, x(n, m)
end subroutine

subroutine matmul(A, B, C)
dim :: m, n, l
integer, intent(in) :: A(m, n), B(n, l)
integer, intent(in) :: C(m, l)
end subroutine
```

Rank is not known, any rank generics:

Index "l" could be a multi-index, representing several dimensions, say "p" dimensions:
```fortran
subroutine matmul(A, B, C)
dim :: p, m, n, l(p)
integer, intent(in) :: A(m, n), B(n, l)
integer, intent(in) :: C(m, l)
end subroutine
```

How do we write a function `sum` that works for any rank? For 1d we can do this:
```fortran
        function mysum_t(a) result(r)
            type(t), intent(in) :: a(:)
            type(t) :: r
            integer :: i
            r = zero_t(a(0))
            do i = 1, size(a)
                r = plus_t(r, a(i))
            end do
        end function
```
how do we extend it to any rank?
```fortran
        function mysum_t(a) result(r)
            dim :: p, L(p)
            type(t), intent(in) :: a(L)
            type(t) :: r
            type(t) :: tmp(size(a))
            integer :: i
            r = zero_t(a(0))
            tmp = reshape(a, [size(a)])
            do i = 1, size(a)
                r = plus_t(r, tmp(i))
            end do
        end function
```
the alternative is to use the existing `..` notation:
```fortran
        function mysum_t(a) result(r)
            type(t), intent(in) :: a(..)
            type(t) :: r
            type(t) :: tmp(size(a))
            integer :: i
            r = zero_t(a(0))
            tmp = reshape(a, [size(a)])
            do i = 1, size(a)
                r = plus_t(r, tmp(i))
            end do
        end function
```

`reshape(X, [....], order=[2, 1])`

**Comment by certik** [comment]
Array concatenation is done using `x = [x, 1, 2, 3]`.

**Comment by ansharlubis** [comment]
[x] Improve the error message in https://github.com/lfortran/lfortran/pull/1168. Done in #1215 
[x] unify instantiate_Function. Done in #1214
[ ] robustness / hardening (more tests and combination of types / arrays). Worked on #1220

**Comment by ansharlubis** [comment]
Support this
```
    write(*,*) generic_sum{real, operator(+), cast_real}(xr) !! expect to print 6.0
    write(*,*) generic_sum{integer, operator(+), cast_integer}(xi) !! expect to print 6
```
To do this we need:
- [ ] Instantiation through templated function calls
- [ ] Instantiation overloading
