### ISSUE TITLE
TODO for IntrinsicFunction

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#1372]
Initial implementation has been implemented in #1371. Now we need to implement the following improvements:

* [ ] add another function, make the API to hook a new function simpler
* [ ] cache the generated functions based on type
* [ ] figure out a solution for separate compilation (minpack), where we should link the functions only once
* [ ] then let's figure out how to get it working for arrays
* [ ] let's use it for "sum" or "minloc", that might be quite simple to get working
* [ ] make the code of `instantiate_LogGamma` simpler by creating some nice API to create ASR

**Comment by certik** [comment]
I wonder if we should lump the generated functions into a module (currently they are global). That way to fix the Minpack issue, we can simply not generate code for the module, and then just compile it at the very end (after generating some default set of routines). This would also take care of the duplication. In a way, it would be almost identical to the current approach, except that we do this in ASR, instead of in the frontend.

**Comment by certik** [comment]
On further thought, I think for now just instantiating the necessary functions in a given translation unit, and ensuring their names are unique in LLVM (across the whole project) would fix the Minpack problem, as we won't need to link anything, except the C library.

Especially for array functions like `sum`, there can be many specializations for array ranks, so it would be quite huge to create all their interfaces.

For modern projects that are all compiled to ASR first, the IntrinsicFunction pass just replaces all such functions in the whole project, so there is no duplication, and they are only instantiated for the types actually used. 

So I would say, let's go with the current global functions design for now, and we'll iterate on this later if needed.
