### ISSUE TITLE
Compiling SciPy

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#1377]
## All SciPy Fortran packages

There were 21 packages in SciPy, now 18.

### Check means package compiles without any source code modification to LLVM.

* [x] amos (compiles)
   * [x] AST -> ASR
   * [x] ASR -> LLVM 
* [x] Minpack (compiles and runs correctly)
* [x] specfun: 
  * [x] AST->ASR: 
    * [x] implicit typing bug: https://github.com/lfortran/lfortran/issues/1378
  * [x] ASR->LLVM: 
    * [x] https://github.com/lfortran/lfortran/issues/1416
    * [x] https://github.com/lfortran/lfortran/issues/1443
    * [x] #1452
* [x] mach
    * [x] AST -> ASR (#556)
* [x] fitpack
    * [x] AST -> ASR:
      * [x] #1447 
* [x] cdflib
    * [x] AST --> ASR
       * [x]  #1088
       * [x] https://github.com/lfortran/lfortran/issues/1836
     * [x] ASR -> LLVM
        * [x] #1973 
        * [x] #1986
* [x] quadpack
   * [x] #2748 
   * [x] AST -> ASR:
     * [x] #1441
* [x] lbfgsb
    * [x] AST -> ASR
    * [x] ASR -> LLVM
* [ ] cobyla
    * [x] AST -> ASR
    * [ ] ASR -> LLVM
* [ ] lbfgsb_src
    * [x] AST -> ASR
    * [ ] ASR -> LLVM
        * [ ] visit_ImpliedDoLoop() not implemented
* [ ] odrpack
    * [ ] #1983 
    * [x] AST -> ASR
      * [x] #768
      * [x] `/scipy/odr/odrpack/d_lpk.f` --> `min0`, `max0`
* [ ] linalg
    * [ ] AST -> ASR
         * [x] #1926
        * [x] `min0`, `max0`
        * [x] https://github.com/lfortran/lfortran/issues/1836
* [ ] odepack: https://github.com/lfortran/lfortran/issues/1650
* [ ] __nnls
    * [x] AST -> ASR
* [ ] dop
    * [x] https://github.com/lfortran/lfortran/issues/1896
    * [ ] #1981 
* [ ] flapack

Removed from SciPy:

* [ ] statlib: https://github.com/lfortran/lfortran/issues/439 (DNE: Does not exists in latest main of SciPy)
    * [x] AST to ASR 
* [ ] Arpack: #1376 
    * [x] #766
    * [x] #768
* [ ] PROPACK
* [ ] slsqp
    * [x] AST -> ASR

## AST -> ASR 
* [x] #661  
* [x] #556 
* [x] data implied do loops: #1088
* [ ] #559 
* [x] #1101 
* [x] https://github.com/lfortran/lfortran/issues/1836
* [x] Implement `--implicit-argument-casting` #1926
* [x] CI: Add `--show-asr` test for every `*.f` file in SciPy
---
## ASR->LLVM
* [ ] Common with union
* [x] Common block with arrays
* [ ] visit_ImpliedDoLoop (https://github.com/lfortran/lfortran/issues/981)
----

### Check means the package compiles without any source modification and all SciPy tests pass and we have a test for it at our CI.

There are 18 packages, we have 9/18 working.

## Specfun

* [x] https://github.com/lfortran/lfortran/issues/1979

## Minpack

* [x] https://github.com/lfortran/lfortran/issues/2203

## Minpack2

* [x] #2752

## Fitpack

* [x] https://github.com/lfortran/lfortran/issues/2345

## Cdflib

* [x] https://github.com/lfortran/lfortran/issues/2342

## Amos

* [x] https://github.com/lfortran/lfortran/issues/2405

## Mach (Special)

* [x] https://github.com/lfortran/lfortran/issues/2612
* [x] remove the workarounds at the CI, ensure original code works

## Quadpack

* [x] https://github.com/lfortran/lfortran/issues/2714

## Mach (Integrate)

* [x] https://github.com/lfortran/lfortran/issues/2754

## Cobyla

* [ ] #2775 

## dop

* [ ] #2755 

----

## Discussion

A discussion regarding status and existence of Fortran codes in SciPy can be found at: https://github.com/lfortran/lfortran/pull/2743

**Comment by certik** [comment]
Here are the list of SciPy packages of of today (SciPy commit 77060bc96ba19098cf0459fd495065b125e2fb7b):
* arpack
* mvndst
* mach
* odepack
* dop
* quadpack
* odrpack
* fitpack
* io
* lbfgsb
* slsqp
* cobyla

**Comment by lucascolley** [comment]
Note that `io` is just [this one small file](https://github.com/scipy/scipy/blob/main/scipy/io/_test_fortran.f), used to test [`scipy.io.FortranFile`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.io.FortranFile.html).
