### ISSUE TITLE
TODO for IntrinsicFunction

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#1406]
* [ ] #1374 
* [ ] get cos/tan, and few other functions ported, let's use macros so that adding them is just adding one line (possibly in few files)
* [ ] add maxloc or sum array function
* [ ] port the rest of the intrinsic elemental functions
* [ ] port the rest of the array functions (all, any, minloc, matmul, transpose, dot_product, etc.)

**Comment by certik** [comment]
I can make progress on this with @Thirumalai-Shaktivel.
