### ISSUE TITLE
SIMD backend

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#2293]
```diff
diff --git a/src/libasr/ASR.asdl b/src/libasr/ASR.asdl
index 26e60e172..d6a29ecef 100644
--- a/src/libasr/ASR.asdl
+++ b/src/libasr/ASR.asdl
@@ -420,6 +420,7 @@ array_physical_type
     = DescriptorArray
     | PointerToDataArray
     | FixedSizeArray
+    | SIMDArray
     | NumPyArray
     | ISODescriptorArray
```
We'll use:
```
from lpython import SIMD
x: Annotated[f32[64], SIMD]
```
In ASR we use `SIMDArray` physical type, and then in the LLVM backend (or ASR->ASR pass) we ensure all such arrays get vectorized, otherwise we give a compile time error message. The conditions are:

* Must be 1D array
* Array element type and all operations must directly map into hardware instructions. For example on Apple M1 CPU, f32 plus and multiply is supported (it will compile), but f16 multiply is not (compile time error on Apple M1)
* Fixed compile time size
* The size must be a multiple of the hardware vector length. If we have 512 bits (AVX-512), the sizeof(element)*size must be equal to 512*n for n=1, 2, 3, .... If n=1, then the array is directly stored in a register. For n>2, the loop is unrolled (since the size is known at compile time), ensuring we hit maximum compute throughput (hide IO and latency).

**Comment by dacarnazzola** [comment]
Extensions!

**Comment by certik** [comment]
I think we need both an extension and a pragma syntax. For pragma, probably this is the way to go:
```fortran
!LF$ attributes simd :: x
real(sp) :: x(8)
```
I asked at https://fortran-lang.discourse.group/t/fortran-syntax-for-pragmas/6532 for feedback.

**Comment by certik** [comment]
With #2452 this now runs: `lfortran --show-c integration_tests/matmul_01.f90`.

Now we have several parallel efforts:
* [ ] Get `matmul_01` working with the C backend
* [ ] Get the `simd` feature working with the C backend
* [ ] Get `matmul_01` working with the LLVM backend
* [ ] Get the `simd` feature working with the LLVM backend

Ordered roughly by the order of priority.

**Comment by rebcabin** [comment]
> Extensions!

Doesn't the question of syntax extensions depend on whether you want code to be compilable by gfortran and flang?

**Comment by rebcabin** [comment]
> Extensions!

Doesn't the question of syntax extensions depend only on whether you want code to be compilable by gfortran and flang?

**Comment by certik** [comment]
> Doesn't the question of syntax extensions depend only on whether you want code to be compilable by gfortran and flang?

Yes. So it's good to have both pragmas and extensions available and users can choose.

**Comment by Shaikh-Ubaid** [comment]
>implement simple simd array, get it working with LLVM and C

@certik  Could you share an example of simple simd array that we expect to work with C and LLVM? Currently, the following seems to work with the `C` backend.

```bash
$ cat examples/expr2.f90 
program pragma2
    !LF$ attributes simd :: A, B, C
    real :: A(8), B(8), C(8)
    A = 1
    B = 2
    C = A + B
end program
$ lfortran examples/expr2.f90 --show-c   

#include <stdlib.h>
#include <stdbool.h>
#include <stdio.h>
#include <string.h>
#include <lfortran_intrinsics.h>


struct dimension_descriptor
{
    int32_t lower_bound, length;
};

struct r32
{
    float *data;
    struct dimension_descriptor dims[32];
    int32_t n_dims;
    bool is_allocated;
};




// Implementations
int main(int argc, char* argv[])
{
    _lpython_set_argv(argc, argv);
    float a __attribute__ (( vector_size(sizeof(float) * 8) ));
    float b __attribute__ (( vector_size(sizeof(float) * 8) ));
    float c __attribute__ (( vector_size(sizeof(float) * 8) ));
    a = (float __attribute__ (( vector_size(sizeof(float) * 8) ))) {(float)(1), (float)(1), (float)(1), (float)(1), (float)(1), (float)(1), (float)(1), (float)(1)};
    b = (float __attribute__ (( vector_size(sizeof(float) * 8) ))) {(float)(2), (float)(2), (float)(2), (float)(2), (float)(2), (float)(2), (float)(2), (float)(2)};
    c = a + b;
    return 0;
}
$ lfortran examples/expr2.f90 --backend c -o tmp
$ ./tmp
$ echo $?
0
```

Is it a good example of simple simd array?

**Comment by certik** [comment]
Excellent! Now we need to build our way to the matmul example, whatever else is needed.

**Comment by Thirumalai-Shaktivel** [comment]
Reference:
- https://gcc.gnu.org/onlinedocs/gcc/Vector-Extensions.html
- https://clang.llvm.org/docs/LanguageExtensions.html#vector-literals

**Comment by certik** [comment]
# Stage Zero

Get the low level  matmul_01 working in LLVM/C backend with and without simd: https://github.com/lfortran/lfortran/issues/2293#issuecomment-1724636639.

# Stage One

Write an ASR->ASR pass that takes code like this:
```python
from timeit import default_timer as clock
import numpy as np

def kernel(A, B, C, x, y, i1, s1):
    # This function computes:
    #C[x:x+6,y:y+16] += np.dot(A[x:x+6,i1:i1+s1], B[i1:i1+s1,y:y+16])

    u = np.empty((6,16), dtype=np.float32) # SIMD
    for i in range(6):
        for j in range(2):
            u[i, j*8:j*8+8] = C[x+i, y+j*8:y+j*8+8]

    Ai = np.empty((8,), dtype=np.float32) # SIMD
    for k in range(i1, i1+s1):
        for i in range(6):
            Ai[:] = A[x+i,k]
            for j in range(2):
                u[i, j*8:j*8+8] += Ai[:] * B[k, y+j*8:y+j*8+8]

    for i in range(6):
        for j in range(2):
            C[x+i, y+j*8:y+j*8+8] = u[i, j*8:j*8+8]

def matmul(A, B, C):
    s3 = 64
    s2 = 120
    s1 = 240

    assert n % s3 == 0
    assert n % s2 == 0
    assert n % s1 == 0
    assert s2 % 6 == 0
    assert s3 % 16 == 0
    C[:,:] = 0

    for i3 in range(0,n,s3):
        for i2 in range(0,n,s2):
            for i1 in range(0,n,s1):
                for x in range(i2,i2+s2,6):
                    for y in range(i3,i3+s3,16):
                        kernel(A, B, C, x, y, i1, s1)


n = 960

A = np.empty((n,n), dtype=np.float32)
B = np.empty((n,n), dtype=np.float32)
C = np.empty((n,n), dtype=np.float32)
A[:,:] = np.random.random((n,n))
B[:,:] = np.random.random((n,n))
t1 = clock()
matmul(A, B, C)
t2 = clock()

C2 = np.dot(A, B)
print(C[:2,:2])
print(C2[:2,:2])
assert np.all(np.isclose(C, C2))

GHz = 1e9
t = t2-t1
fma_clock = 0.0625
freq = 3.2*GHz
measured = t * freq / n**3
percent_peak = fma_clock / measured * 100
print(f"Size (n x n): n = {n}")
print(f"Size MB: {4*n*n/1024**2}")
print(f"Time: {t}s")
print("Clock cycles per element:")
print(f"Theoretical performance peak: {fma_clock} cycles")
print(f"Measured:                     {measured} cycles")
print(f"Percent peak:                 {percent_peak}%")
```
And generates code from stage zero, and thus gets peak performance.

# Stage Two

Generate the code in stage one from this code:

```python
C[:,:] = 0
for i in range(n):
    for k in range(m):
        for j in range(l):
            C[i,j] += A[i,k]*B[k,j]
```

**Comment by certik** [comment]
TODO:

The simd array translates to a SIMD instruction, say `VFMADD231PDx` on x86. The idea is to use these with vector operations in ASR, then it translates nicely to the SIMD instructions. I was thinking initially to just be static local arrays, like `real, simd :: A(8)`, and the length must agree exactly with the hardware SIMD size. So I think likely not allocatable at first.

If you want to work on this, then I recommend not worrying about error messages at first, but rather focus on getting an end-to-end example working first. Take a platform (x86 or arm) and take some simple vector addition, write an example that manually splits it into simd arrays (so instead of do `i = 1, n` you have `do i = 1, n, 8` and in the inner loop you do another `do j = i+0, i+7` or something like that over the simd array. Then ensure LLVM generates the simd operations and check it with a reference test.

Then we'll expand it to more operations, this will provide the foundation. We'll then give error messages if the vector operation on simd arrays cannot be represented as a SIMD operation. So that we guarantee that simd arrays always generate the expected vector instructions.

Initially we'll program these manually. Only once the backend works and manual code works then we'll add ASR->ASR pass that takes a scalar loop and vectorizes it, all in ASR using the simd primitives.

**Comment by opixdown** [comment]
@certik I was able to get an end to end simd example working on ARM (Apple Silicon).

## Test Program

```fortran
program simd
    implicit none
    real :: va(8), vb(8), vc(8)
    !LF$ attributes simd :: va, vb, vc
    integer :: i

    do i = 1, 8
        va(i) = real(i)
        vb(i) = real(i * 2)
    end do

    vc = va + vb

    print *, "vc(1) = ", vc(1)
    print *, "vc(8) = ", vc(8)
end program simd
```

## Output

```
vc(1) =     3.00000000e+00
vc(8) =     2.40000000e+01
```

## ASR 
The following output from  --show-asr shows that all SIMD annotated arrays are marked as SIMDArray:

```

                                        SIMDArray
                                    )
                                    ()
                                    Source
                                    Public
                                    Required
--
                                        SIMDArray
                                    )
                                    ()
                                    Source
                                    Public
                                    Required
--
                                        SIMDArray
                                    )
                                    ()
                                    Source
                                    Public
                                    Required
```

## LLVM 
The generated LLVM IR contains a vector addition on <8 x float>:
```
%27 = load <8 x float>, <8 x float>* %vb, align 32
%28 = load <8 x float>, <8 x float>* %va, align 32
%29 = fadd <8 x float> %28, %27
store <8 x float> %29, <8 x float>* %vc, align 32
```

## Machine Code 
Inspecting the final binary with otool -tV shows 

```
fadd.4s v1, v2, v1
fadd.4s v0, v3, v0
```
This confirms the SIMD operation survives all the way from Fortran source to real hardware SIMD instructions

**Comment by opixdown** [comment]
With the end to end SIMD path working, can we now add the stricter semantic checks in process_simd_variables().

**Comment by certik** [comment]
Excellent, this indeed already works. Now let's analyze our SIMD tests, we have three:
```
integration_tests/matmul_01.f90
integration_tests/simd_01.f90
integration_tests/simd_02.f90
```
They all run with `llvm` in integration tests, so that's good. We test ASR for `matmul_01.f90` in tests, but not the other two. And we do not test LLVM nor assembly output.

From your output it seems LLVM can represent vector operations directly, at least for addition, which is nice. We should look into it if that's the way to go, but if so, then we don't need to test assembly, just the LLVM output. So let's add LLVM tests for the two simd tests. The other thing to consider is to improve our testing infrastructure to also require specific LLVM operations, namely, that the reference LLVM output contains:
```
  %2 = load <8 x float>, <8 x float>* %vb, align 32
  %3 = load <8 x float>, <8 x float>* %va, align 32
  %4 = fadd <8 x float> %3, %2
  store <8 x float> %4, <8 x float>* %vc, align 32
```
It loads a vector, then it adds a vector, then it stores a vector.

Next, we need to investigate how LLVM handles sizes that do not map to hardware. For example, does LLVM allow `<7 x float>`?  At some point I am guessing it will give an error. Or will it rewrite it to non-vector operations? Is the `<8 x float>` thus hardware independent, or already dependent? We need to decide how to handle errors, specifically:
```fortran
    real :: va(7)
    !LF$ attributes simd :: va
```
Either we need to check that this always generates `<7 x float>` and LLVM is always fine with it, then I think it might be ok. Otherwise we need to create an error in the LLVM backend. However, `<7 x float>` doesn't map to a SIMD instruction on Apple nor x86, so at some point somebody should give an error. So we need to investigate if LLVM can reliably give these errors, otherwise we need to somehow do it. If LLVM doesn't give realiable errors, then we need to figure out how to query the LLVM backend what the vector instructions lengths are, and then give errors ourselves in the LLVM backend. In fact this might be the way to do it anyway, so that we give nice error messages.

Regarding errors in AST->ASR, I would only accept `real :: A(n)` where `n` is either an integer constant, or an integer parameter (so we know the value at compile time), nothing else is allowed. The types can be integer and real. I would disallow all other attributes at first. So no allocatable, etc. We should allow it as function arguments though, I think that maps cleanly to hardware.

**Comment by opixdown** [comment]
Thanks @certik , I went through all three SIMD tests and verified the LLVM behavior in detail.
snipets:

## simd_01.f90 (size 8)
```
 %26 = load <8 x float>, <8 x float>* %b, align 32
  %27 = load <8 x float>, <8 x float>* %a, align 32
  %28 = fadd <8 x float> %27, %26
  store <8 x float> %28, <8 x float>* %c, align 32
```

## simd_02.f90 (size 4)
```
  %268 = load <4 x float>, <4 x float>* %b, align 16
  %269 = fmul <4 x float> %268, %267
  %270 = load <4 x float>, <4 x float>* %a, align 16
  %271 = fadd <4 x float> %270, %269
```
## matmul_01.f90
```

  %2633 = fmul <8 x float> %2632, %2631
  %2634 = load <8 x float>, <8 x float>* %u50, align 32
  %2635 = fadd <8 x float> %2634, %2633
  store <8 x float> %2635, <8 x float>* %u50, align 32
  %2636 = load i32, i32* %y, align 4
```

All of them already generate true LLVM vector operations. we are just not asserting it in the test infrastructure yet.And I agree that testing LLVM IR is sufficient as LLVM can directly represent SIMD using vector types. 

## Non hardware vector sizes 
I investigated this LLVM does allow arbitrary vector sizes i tests with size 3,5,7. for eg.

Code
```
program size3
    real :: va(3), vb(3), vc(3)
    !LF$ attributes simd :: va, vb, vc
    vc = va + vb
end program size3
```
output:
```
  %va = alloca <3 x float>, align 16
  %vb = alloca <3 x float>, align 16
  %vc = alloca <3 x float>, align 16
  %2 = load <3 x float>, <3 x float>* %vb, align 16
  %3 = load <3 x float>, <3 x float>* %va, align 16
  %4 = fadd <3 x float> %3, %2
  store <3 x float> %4, <3 x float>* %vc, align 16
```

as LLVM does not error out or write these to scalar operations. It looks like that ` <n x float> `is a hardware independent vector abstraction in LLVM. so i think restricting sizes to 4/8/16 in semantic not look necessary.

if we want to enforce single hardware SIMD instructions so we will need to do it in backend.LLVM itself does not provide such errors.

**Comment by opixdown** [comment]
@certik I think we can now proceed to add LLVM checks for the tests and keepin semantic checks limited to only the cases you mentioned. one thing i am not clear on what is the best way to verify LLVM output in our tests. how we usually verify specific LLVM patterns?

**Comment by certik** [comment]
We don't verify LLVM patterns currently, just the full reference test. LLVM has a tool called "LIT" which allows to find specific strings (in order) in the reference output. We could implement something similar if needed.

So it seems at the ASR level we can represent any SIMD length as well. However, in the ASR->LLVM, we should query the LLVM backend what SIMD lengths are allowed and error out loudly. The idea is that the SIMD array will always translate to a SIMD instruction, or give an error. We'll also need some mechanisms to ask about these lengths earlier on, as we'll add ASR->ASR vectorization passes (that will need to know what length to use).
