### ISSUE TITLE
C++ AST TODO

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#237]
*Original issue*: https://gitlab.com/lfortran/lfortran/-/issues/139

* [ ] Add a visitor that raises an exception if a method is visited and not implemented. Test that the exception is raised.
* [x] Generate the pickle visitor automatically (as a base class, then subclass it to provide customized shorter print for a few selected types)
* [ ] Make Allocator allocate another chunk of memory and keep track of the chunks, and free them all at the end
* [ ] Make Str and Vec more similar to std::string and std::vector, e.g., add operator[] to Vec, etc.
* [x] Make `sep` part of a `statement`, possibly adjust location info & test that the location info is correct
* [x] Parse `.eq.`
* [ ] Parse some real Fortran into AST
* [x] Implement location tracking + nice syntax error messages
* [ ] Split the visitors to `ast_visitors.h` and `make_*` functions into `ast_make.h`, so that `ast.h` only contains the definitions but no code: make all headers only depend on `ast.h`, and the `ast_visitor.h` and `ast_make.h` will only be included in cpp files. To speedup compilation.
* [ ] Generate Python wrappers
* [ ] Switch ANTLR based parser to this C++ parser, make all (unmodified) tests pass
