### ISSUE TITLE
C++ TODO

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#238]
*Original issue*: https://gitlab.com/lfortran/lfortran/-/issues/140

Initial C++ LLVM evaluation implementation is there.

TODO:

* [x] LLVMEvaluator class and tests just like in Python
* [x] initial ASR, with pickling
* [ ] implement s-expression readers (both AST and ASR)
* [x] initial ASR->LLVM, test it from ASR s-expressions
* [x] initial AST->ASR, test it using AST s-expressions
* [ ] FortranEvaluator class and tests as in Python

After this we will have the initial self-contained compiler in C++ only (no Python dependencies).

See also https://gitlab.com/lfortran/lfortran/-/issues/139.
