### ISSUE TITLE
Generics TODO

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#2474]
High priority:

* [x] Implement a `qsort` example: https://github.com/lfortran/lfortran/issues/2266 
-> handled in #2956, #2964 (with struct types)
* [x] Implement a lapack example: https://github.com/lfortran/lfortran/issues/2267
-> handled in #2963
* [x] https://github.com/lfortran/lfortran/issues/2508
-> handled in #2973
* [ ] Documentation
  * [ ] Document how generics are represented at the ASR level, add all the generic nodes into https://github.com/lfortran/lfortran/tree/main/doc/src/asr/asr_nodes:
    * [ ] Requirement
    * [ ] Template
    * [ ] TypeParameter
  * [ ] How instantiation works at the ASR level: perhaps add a document `generics.md` with a Fortran example, and the corresponding ASR and how everything works: what `libasr` functions to call to instantiate
  * [ ] How the type checking works
  * [ ] Only if there is time, we can also document the frontend parts

Medium priority

* [ ] https://github.com/lfortran/lfortran/issues/2814
  * [ ] Detailed list of all issues to fix: https://github.com/lfortran/lfortran/issues/2814#issuecomment-1898876724
* [ ] Add tests for error messages, select several typical ones, ensure the error message is good
* [ ] Update dev.lfortran.org with examples, just a few that works, and add tested error messages as comments
* [ ] Add another test for `generic_avg` to be "reduction" and add "min" as a test, see #2508 for an example
* [ ] Implement sparse matrix example: https://github.com/lfortran/lfortran/issues/2316
* [ ] Nested templates: `{matrix_type=csc_matrix{T=real},...}`: these would be two separate instantiations, so might still be first order templates
* [ ] Add a dedicated section about generics at docs.lfortran.org, document how it is implemented in LFortran, as well as add a nice video explaining how it works internally, both for LFortran developers as well as for developers of other Fortran compilers to help them implement generics
* [x] https://github.com/lfortran/lfortran/issues/2991
-> handled in #2995 
* [x] https://github.com/lfortran/lfortran/issues/2992
-> handled in #2995 
* [x] Add a test for `templates_simple_02` where we pass in a user defined derived type (struct) and it will still work
-> the template sort in #2964 has struct passed into template
* [x] Support `integer` as a type in requirements `requires operator_r(T, integer, T, div)`
  -> handled in #2553
* [x] Get `generic_avg` working, here is an example: https://github.com/certik/lfortran/commit/3474a7379b04c5b6c913a90da5fbbc6073a43716, which compiles and runs. But when the instantiation lines are uncommented, it will fail to compile
  -> handled in #2553 

Lower Medium priority

* [ ] `y = plus(y, times(a,  x))` https://github.com/lfortran/lfortran/issues/2771#issuecomment-1793603472
* [ ] `interface axpy` https://github.com/lfortran/lfortran/issues/2771#issuecomment-1793603472
* [ ] main program without "program" and templates (we have some heuristics to tackle this, and I think it might not work for a template) https://github.com/lfortran/lfortran/issues/2771#issuecomment-1793603472
* [ ] Figure out improvements to casting: at least for intrinsic types (`integer`, `real`, etc.) it should be semi-automatic, so that you don't need to write these manual `cast_to_T` functions
* [ ] Support keyword arguments (for readability):
  * [ ] In instantiation `generic_sum{add=add_my_type, cast=integer_to_my_type}(xmt)`
  * [ ] In requirements `cast_r(T=integer, U=T, cast=cast_to_T)`
* [ ] Support `type, deferred :: T*` 
* [x] Get operators +, *, /, - working for simple generics
* [x] Support `requires :: operator_r(T, T, T, add), cast_r(T, cast_to_T)`
  -> handled in #2518 

Low priority:

* [ ] Figure out and design default arguments to be used at instantiation and requirement specifications, by looking the same name in the scope, and use it if found (unambiguously)
* [ ] Type inference at instantiation
* [x] `require` vs `requires` (to be discussed with the committee)

**Comment by ansharlubis** [comment]
Suggestions:
- [ ] Improve reuse for templated functions with same signature (currently new function is generated for each template instantiation)
