### ISSUE TITLE
Improvements to the binary tarball

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#259]
*Original issue*: https://gitlab.com/lfortran/lfortran/-/issues/179

* [ ] Get the default dynamic linking working (https://gitlab.com/lfortran/lfortran/-/issues/178)
* [ ] Make it work without specifying `LFORTRAN_RUNTIME_LIBRARY_DIR` (https://gitlab.com/lfortran/lfortran/-/issues/180)
* [ ] Add a few examples that work with the compiler already (https://gitlab.com/lfortran/lfortran/-/issues/181)
* [ ] Add a README
