### ISSUE TITLE
Fortran Features Roadmap

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#297]
*Original issue*: https://gitlab.com/lfortran/lfortran/-/issues/272

This is an LFortran roadmap of Fortran features to implement. This is a general roadmap. See https://gitlab.com/lfortran/lfortran/-/issues/313 for a roadmap for MVP (minimum viable product).

The parser [parser.yy](https://gitlab.com/lfortran/lfortran/-/blob/master/src/lfortran/parser/parser.yy) is nearly complete, but not everything from it is converted yet to AST, ASR and LLVM. Below we list all such features. This list is not comprehensive, but it covers most features to start compiling a lot of production codes.

Each feature should be defined by adding a test (https://gitlab.com/lfortran/lfortran/-/issues/276), and if that test works (AST, ASR and LLVM), it is marked as implemented. We mark a feature below as complete (we check the box) if the main part of the feature works (in LLVM), but not necessarily all the corner cases. As more corner cases are discovered or reported, we will open new issues and link them here to the particular feature as needed.

# Fortran Features

* Intrinsic functions (blocker: https://gitlab.com/lfortran/lfortran/-/issues/247): see https://gitlab.com/lfortran/lfortran/-/wikis/Implementation%20Status%20of%20Intrinsic%20Functions for a comprehensive list
  * [x] basic (exp, abs)
  * [x] trigonometric (sin, cos, tan) (https://gitlab.com/lfortran/lfortran/-/merge_requests/717)
  * [ ] special (bessel)
  * [x] kind
  * [x] real
  * [x] int
  * [] character
  * [x] achar
  * [x] len
  * [x] trim
  * [x] len_trim
  * [x] aimag
  * [ ] ichar
  * [x] ishft(https://gitlab.com/lfortran/lfortran/-/merge_requests/1563)
  * [x] ieor(https://gitlab.com/lfortran/lfortran/-/merge_requests/1531)
  * [ ] epsilon
  * [ ] index
  * [ ] adjustl
  * [ ] random_seed, random_number
  * [x] system_clock (https://gitlab.com/lfortran/lfortran/-/merge_requests/1562)
  * [ ] open, close, read, write (https://gitlab.com/lfortran/lfortran/-/issues/563)
  * [ ] get_environment_variable
  * [ ] merge
  * [ ] pack
* Arrays
  * [x] Declaring 1D arrays
  * [x] Passing 1D arrays to / from procedures
  * [ ] N-dimensional arrays
  * Array operations
    * [ ] Slicing (`A(1:3) = 5`)
    * [ ] Array arithmetics (`a = x + y` where `a`, `x`, `y` are arrays)
  * [x] Allocatable arrays
  * [ ] assumed-shape (https://gitlab.com/lfortran/lfortran/-/issues/50)
  * [ ] explicit-shape (https://gitlab.com/lfortran/lfortran/-/issues/51)
  * [ ] elemental procedures
  * [ ] array initializers
  * Array intrinsic functions
    * [x] size
    * [ ] sum
    * [ ] matmul
    * [ ] dot_product
    * [ ] minval, maxval
    * [ ] all, any
* Statements
  * [x] Select Case (https://gitlab.com/lfortran/lfortran/-/merge_requests/703)
  * [x] Associate construct
  * [ ] Open/close/read/write/inquire/rewind statement
  * [ ] Where statement
  * [ ] Forall
  * [ ] Infinite do loop
  * [ ] do concurrent
  * [ ] format
  * [ ] Block statement
* Expressions
  * [ ] Generator expression
  * [x] BOZ constants
  * [x] String concatenation (https://gitlab.com/lfortran/lfortran/-/merge_requests/716, https://gitlab.com/lfortran/lfortran/-/merge_requests/735)
* Declarations and types:
  * [x] iso_c_binding
  * [x] real and complex kinds (single, double, quadruple) (https://gitlab.com/lfortran/lfortran/-/issues/96)
  * [x] interface blocks (https://gitlab.com/lfortran/lfortran/-/issues/252)
  * [x] parameters
  * [ ] Derived types (https://gitlab.com/lfortran/lfortran/-/issues/273)
  * [x] Strings (`character`) (https://gitlab.com/lfortran/lfortran/-/merge_requests/712, https://gitlab.com/lfortran/lfortran/-/merge_requests/713, https://gitlab.com/lfortran/lfortran/-/merge_requests/735, https://gitlab.com/lfortran/lfortran/-/issues/286, https://gitlab.com/lfortran/lfortran/-/issues/296)
  * [x] Pointers (https://gitlab.com/lfortran/lfortran/-/merge_requests/721)
  * [ ] Allocatable strings (might need special attention)
  * [ ] Allocatable types (other than strings)
  * [ ] Enumerations
  * [x] Operators and assignment overloading
  * [ ] Namelists
  * [ ] Save variables
  * [ ] Handling of `implicit none` (currently it is ignored and assumed it is in effect)
  * [ ] class types with methods, inheritance (https://gitlab.com/lfortran/lfortran/-/issues/274)
* Procedures
  * [ ] Passing procedures as arguments to procedures (callbacks) (https://gitlab.com/lfortran/lfortran/-/merge_requests/917)
  * [ ] Nested procedures (https://gitlab.com/lfortran/lfortran/-/merge_requests/746, https://gitlab.com/lfortran/lfortran/-/merge_requests/920)
  * [ ] Optional arguments (`optional`, `present`)
  * [ ] Pure procedures
* Modules
  * [x] modules (intrinsic and non intrinsic) (https://gitlab.com/lfortran/lfortran/-/issues/18)
  * [ ] Submodules

Candidate codes to get working:

* https://github.com/lanl/SNAP (Fortran 95) https://gitlab.com/lfortran/lfortran/-/issues/313
* https://github.com/certik/dftatom (Fortran 95) https://gitlab.com/lfortran/lfortran/-/issues/319
* https://github.com/planelles20/numerical-methods-fortran

The [Compiler Support for the Fortran 2003 and 2008 Standards](https://www.physics.muni.cz/~jancely/NM/Texty/Fortran/PorovnaniFortranu.pdf) has a good high level list of features to be supported that we can use once we get there.
