### ISSUE TITLE
Compiling stdlib special functions

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#3000]
Issues to fix:

High priority (no workaround):

* [x] `cmplx(d(0)...` https://github.com/lfortran/lfortran/issues/3014
* [x] `d = hypot(z2 % re, z2 % im)`(#3011)
* [x] `sum % im = sum % im + 2 * pi * m * sign(1.0_sp, z % im)` ( https://github.com/lfortran/lfortran/issues/3013 )
* [x] `anint` ( https://github.com/lfortran/lfortran/issues/3009 )
* [x]  `mod(p, two)` ( https://github.com/lfortran/lfortran/pull/3002 )

Medium priority (workaround works):

* [x] `gamma` had to be renamed to `mgamma` (https://github.com/lfortran/lfortran/issues/3019)
* [ ] mod file hack in `build.sh` https://github.com/lfortran/lfortran/issues/3047
* [ ] `error_stop` missing at link time
  * [ ] `module procedure` interface support 
  * [ ] submodule
* [ ] `real128` (#2999)

-------------

https://github.com/certik/stdlib/pull/new/lf7

With a11ebf662a437b45fd54bb9a58a769a8f76bfb69 and the following diff:
```diff
--- a/src/stdlib_specialfunctions_gamma.fypp
+++ b/src/stdlib_specialfunctions_gamma.fypp
@@ -3,7 +3,7 @@
 #:include "common.fypp"
 #:set CI_KINDS_TYPES = INT_KINDS_TYPES + CMPLX_KINDS_TYPES
 module stdlib_specialfunctions_gamma
-    use iso_fortran_env, only : qp => real64
+    use iso_fortran_env, only : qp => real128
     use stdlib_kinds, only :  sp, dp, int8, int16, int32, int64
     use stdlib_error, only : error_stop
```

All tests pass with GFortran:
```console
$ FC=gfortran cmake .
$ make
$ ctest 
Test project /Users/ondrej/repos/fortran-lang/stdlib
      Start  1: always_skip
 1/13 Test  #1: always_skip ......................***Skipped   0.01 sec
      Start  2: always_fail
 2/13 Test  #2: always_fail ......................   Passed    0.00 sec
      Start  3: test-drive/all-tests
 3/13 Test  #3: test-drive/all-tests .............   Passed    0.01 sec
      Start  4: test-drive/check
 4/13 Test  #4: test-drive/check .................   Passed    0.00 sec
      Start  5: test-drive/select
 5/13 Test  #5: test-drive/select ................   Passed    0.00 sec
      Start  6: specialfunctions_gamma
 6/13 Test  #6: specialfunctions_gamma ...........   Passed    0.00 sec
      Start  7: gamma
 7/13 Test  #7: gamma ............................   Passed    0.00 sec
      Start  8: gamma_p
 8/13 Test  #8: gamma_p ..........................   Passed    0.00 sec
      Start  9: gamma_q
 9/13 Test  #9: gamma_q ..........................   Passed    0.00 sec
      Start 10: ligamma
10/13 Test #10: ligamma ..........................   Passed    0.00 sec
      Start 11: log_factorial
11/13 Test #11: log_factorial ....................   Passed    0.00 sec
      Start 12: log_gamma
12/13 Test #12: log_gamma ........................   Passed    0.00 sec
      Start 13: uigamma
13/13 Test #13: uigamma ..........................   Passed    0.00 sec

100% tests passed, 0 tests failed out of 13

Total Test time (real) =   0.06 sec

The following tests did not run:
	  1 - always_skip (Skipped)
```

**Comment by certik** [comment]
Using the lf8 branch, gfortran still passes all tests, now only examples are tested.

And with LFortran:

```console
$ FC=gfortran cmake .
$ make
$ cp src/*.mod example/specialfunctions_gamma
$ make
$ ctest 
```

**Comment by certik** [comment]
Using `lf9`, this now compiles and runs:
```console
$ ./build.sh
[...]
[ 92%] Building Fortran object example/specialfunctions_gamma/CMakeFiles/example_gamma.dir/example_gamma.f90.o
[100%] Linking Fortran executable example_gamma
[100%] Built target example_gamma
+ ./example/specialfunctions_gamma/example_gamma
362880
```

**Comment by certik** [comment]
To see the workarounds that we needed to do, use `lf12` and:
```console
$ git diff a11ebf6..9897ea3
```

**Comment by Pranavchiku** [comment]
Implementation `anint` will be similar to `aint`, just that `anint` will round off to nearest whole number. It will be an easy fix.

**Comment by Pranavchiku** [comment]
Perfect. With `lf12`, I get all tests passed, I am looking at diff and will try to fix as much as I can :)

**Comment by Pranavchiku** [comment]
We have PRs for all high priority tasks ready. We can remove corresponding workarounds once those are merged.

**Comment by Pranavchiku** [comment]
Simplified commits and pushed at https://github.com/Pranavchiku/stdlib-fortran-lang/tree/lf13

**Comment by certik** [comment]
@Pranavchiku go ahead and remove workarounds that are now fixed. Let's update the CI.

**Comment by certik** [comment]
The current status of workarounds sorted by priority:

* test-drive
* mgamma
* submodule support for error stop
* narrowing down to only special functions
* quadruple precision

**Comment by Pranavchiku** [comment]
`mgamma` works, fix was through #3032, thanks to @Thirumalai-Shaktivel :)

**Comment by certik** [comment]
Does it print exactly the same results as in GFortran?

**Comment by Pranavchiku** [comment]
Didn't check yet, will do in a while.

**Comment by Pranavchiku** [comment]
I checked and pushed at https://github.com/pranavchiku/stdlib-fortran-lang/tree/lf-special-function-gamma-3, the results align with GFortran.

Moreover added `error stop` checks, and updated CI via #3339.

**Comment by Pranavchiku** [comment]
I will suggest not to close these issues unless every workaround is removed.
cc @czgdp1807

**Comment by czgdp1807** [comment]
The only thing left here is ``real128``. https://github.com/lfortran/lfortran/pull/3037 should be done at highest priority and then revert https://github.com/lfortran/lfortran/commit/07af3c505e5a7b68815de09cc3f4a68afecc11b1 as well.
