### ISSUE TITLE
Compiling stdlib math

### ISSUE THREAD

**Issue by Pranavchiku** [lfortran/lfortran#3046]
Using [lf-math](https://github.com/Pranavchiku/stdlib-fortran-lang/tree/lf-math) branch, gfortran works well.

With LFortran

```
FC=lfortran cmake .
make fortran_stdlib
cp src/*.mod example/math
make
./example/math/example_clip_integer
./example/math/example_clip_real
./example/math/example_diff
./example/math/example_gcd
./example/math/example_linspace_complex
./example/math/example_linspace_int16
./example/math/example_logspace_complex
./example/math/example_logspace_int
./example/math/example_logspace_rstart_cbase
./example/math/example_math_all_close
./example/math/example_math_arange
./example/math/example_math_arg
./example/math/example_math_argd
./example/math/example_math_argpi
./example/math/example_math_is_close
```

----

Examples: 

* [x] example_clip_integer
* [x] example_clip_real
* [x] example_diff #3298
* [x] example_gcd
* [x] example_linspace_complex #3276
* [x] example_linspace_int16 #3265
* [x] example_logspace_complex #3276
* [x] example_logspace_int #3276
* [x] example_logspace_rstart_cbase #3276
* [x] example_math_all_close #3249 #3250
* [x] example_math_arange
* [x] example_math_arg #3172 
* [x] example_math_argd #3172 
* [x] example_math_argpi #3172 
* [x] example_math_is_close #3181

Tick means it works with LFortran ( generates output, not sure if it aligns with GFortran )

----
Branch: https://github.com/Pranavchiku/stdlib-fortran-lang/commits/lf-math9
Workarounds to remove:

* [ ] https://github.com/Pranavchiku/stdlib-fortran-lang/commit/076c6e284f17531a72b028f766588d92adb23b74
* [ ] submodule
* [ ] https://github.com/Pranavchiku/stdlib-fortran-lang/commit/578ec4253e6f4dc0fb6618939a32c8053de753c8

---

Issues to fix:
* [ ] `stdlib_math_diff` fails to generate LLVM
    * [x] https://github.com/lfortran/lfortran/issues/3051
* [x] `stdlib_math_is_close` fails to generate LLVM ( fails at ASR -> ASR Pass )  ( Works, as shifted to stdlib_math)
    * [x] https://github.com/lfortran/lfortran/issues/3054
 * [x] `example_math_is_close.f90` 
     * [x]  https://github.com/lfortran/lfortran/issues/3057
     * [x] #3180
 * [x] `stdlib_math_arange.f90`
     * [x] https://github.com/lfortran/lfortran/issues/3060
     * [x] https://github.com/lfortran/lfortran/pull/3073
     * [ ] https://github.com/lfortran/lfortran/issues/3082
* [ ] https://github.com/lfortran/lfortran/issues/3166
* [x] example_math_argxx.f90 https://github.com/lfortran/lfortran/issues/3171
* [ ] example_math_all_close
    * [x] https://github.com/lfortran/lfortran/issues/3182
    * [x] #3244 
    * [ ] https://github.com/lfortran/lfortran/issues/3251
* [x] example_linspace_int16.f90
    * [x]  #3264

**Comment by Pranavchiku** [comment]
```console
+ make fortran_stdlib
[  4%] Generating stdlib_optval.f90
[  9%] Generating stdlib_kinds.f90
[ 14%] Generating stdlib_math.f90
[ 19%] Generating stdlib_math_all_close.f90
[ 23%] Generating stdlib_math_arange.f90
[ 28%] Generating stdlib_math_diff.f90
[ 33%] Generating stdlib_math_is_close.f90
[ 38%] Generating stdlib_math_linspace.f90
[ 42%] Generating stdlib_math_logspace.f90
[ 47%] Building Fortran object src/CMakeFiles/fortran_stdlib.dir/stdlib_kinds.f90.o
[ 52%] Building Fortran object src/CMakeFiles/fortran_stdlib.dir/stdlib_optval.f90.o
[ 57%] Building Fortran object src/CMakeFiles/fortran_stdlib.dir/stdlib_error.f90.o
[ 61%] Building Fortran object src/CMakeFiles/fortran_stdlib.dir/f08estop.f90.o
style suggestion: Use 'end if' instead of 'endif'
  --> /Users/pranavchiku/repos/stdlib/src/f08estop.f90:38:1
   |
38 | endif
   | ^^^^^ help: write this as 'end if'


Note: Please report unclear or confusing messages as bugs at
https://github.com/lfortran/lfortran/issues.
[ 66%] Building Fortran object src/CMakeFiles/fortran_stdlib.dir/stdlib_math.f90.o
[ 71%] Building Fortran object src/CMakeFiles/fortran_stdlib.dir/stdlib_math_all_close.f90.o
[ 76%] Building Fortran object src/CMakeFiles/fortran_stdlib.dir/stdlib_math_arange.f90.o
[ 80%] Building Fortran object src/CMakeFiles/fortran_stdlib.dir/stdlib_math_diff.f90.o
[ 85%] Building Fortran object src/CMakeFiles/fortran_stdlib.dir/stdlib_math_is_close.f90.o
[ 90%] Building Fortran object src/CMakeFiles/fortran_stdlib.dir/stdlib_math_linspace.f90.o
[ 95%] Building Fortran object src/CMakeFiles/fortran_stdlib.dir/stdlib_math_logspace.f90.o
[100%] Linking Fortran static library libfortran_stdlib.a
warning: /Library/Developer/CommandLineTools/usr/bin/ranlib: archive library: libfortran_stdlib.a the table of contents is empty (no object file members in the library define global symbols)
[100%] Built target fortran_stdlib
+ cp src/estop.mod src/stdlib_error.mod src/stdlib_kinds.mod src/stdlib_math.mod src/stdlib_math_all_close.mod src/stdlib_math_arange.mod src/stdlib_math_diff.mod src/stdlib_math_is_close.mod src/stdlib_math_linspace.mod src/stdlib_math_logspace.mod src/stdlib_optval.mod example/math
+ make
[ 41%] Built target fortran_stdlib
[ 43%] Building Fortran object example/math/CMakeFiles/example_clip_integer.dir/example_clip_integer.f90.o
[ 45%] Linking Fortran executable example_clip_integer
[ 45%] Built target example_clip_integer
[ 47%] Building Fortran object example/math/CMakeFiles/example_clip_real.dir/example_clip_real.f90.o
[ 49%] Linking Fortran executable example_clip_real
[ 49%] Built target example_clip_real
[ 50%] Building Fortran object example/math/CMakeFiles/example_diff.dir/example_diff.f90.o
[ 52%] Linking Fortran executable example_diff
ld: Undefined symbols:
  _diff_1_int32_x, referenced from:
      _main in example_diff.f90.o
      _main in example_diff.f90.o
      _main in example_diff.f90.o
  _diff_1_sp_x, referenced from:
      _main in example_diff.f90.o
  _diff_2_int32_x, referenced from:
      _main in example_diff.f90.o
clang: error: linker command failed with exit code 1 (use -v to see invocation)
The command 'clang -o example_diff CMakeFiles/example_diff.dir/example_diff.f90.o ../../src/libfortran_stdlib.a  -L"/Users/pranavchiku/repos/lfortran/src/bin/../runtime" -Wl,-rpath,"/Users/pranavchiku/repos/lfortran/src/bin/../runtime" -llfortran_runtime -lm' failed.
make[2]: *** [example/math/CMakeFiles/example_diff.dir/build.make:97: example/math/example_diff] Error 10
make[1]: *** [CMakeFiles/Makefile2:1029: example/math/CMakeFiles/example_diff.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
```

**Comment by certik** [comment]
It looks like it builds some binaries, but not all. So just comment out the failing builds and build at least something. Then we'll go from there.

**Comment by Pranavchiku** [comment]
With the latest commit, it builds everything and examples run, quite a few things are commented, I'll segregate commits correctly so that those make more sense.

A common error `Undefined symbols: xx, referenced from: `.

**Comment by Pranavchiku** [comment]
Current status: https://github.com/Pranavchiku/stdlib-fortran-lang/commits/lf-math3/

**Comment by Pranavchiku** [comment]
Latest branch: https://github.com/Pranavchiku/stdlib-fortran-lang/commits/lf-math7/

We have all examples working except `example_diff.f90`.

**Comment by certik** [comment]
It seems the examples above are not being run at the CI: https://github.com/lfortran/lfortran/issues/3482
