### ISSUE TITLE
MVP: Roadmap to compile the SNAP project

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#318]
*Original issue*: https://gitlab.com/lfortran/lfortran/-/issues/313

The roadmap at https://gitlab.com/lfortran/lfortran/-/issues/272 is a general roadmap. In this issue I am listing a specific roadmap to compile just one project:

https://github.com/lanl/SNAP

Once we can compile it, we can release an MVP (minimum viable product) of LFortran. This project is a great target for MVP because it is not written by me, thus this will be useful to people, it uses Fortran 95, it's about 8000 lines of code, and the MPI can be turned off, it is a proxy app for a bigger production code. It is within reach. To compile it, we do not need to implement Fortran features in all generality, just enough to compile SNAP.

# Roadmap

Parsing and AST now works. We are now working on ASR, see below.

## Parsing

There are only 4 small issues, otherwise LFortran can parse everything.

LFortran issues:

* [x] Label after `cycle`: https://gitlab.com/lfortran/lfortran/-/issues/317
* [x] More complicated generator expressions: https://gitlab.com/lfortran/lfortran/-/issues/315

SNAP seems to be using two extensions, which might be fixed in SNAP itself, or we can implement them in LFortran:

* [x] Missing comma after / in format specification (works in NAG, but seems not standard conforming): https://gitlab.com/lfortran/lfortran/-/issues/314 (we fixed it in LFortran), https://github.com/lanl/SNAP/pull/13
* [ ] Missing comma between strings in format specification (fails in the NAG compiler also): https://gitlab.com/lfortran/lfortran/-/issues/316, https://github.com/lanl/SNAP/pull/17

## AST

We can test that AST is correct file by file using `lfortran fmt -i analyze.f90` which overwrites the file by going from AST to source code. At this point the LFortran master can translate all files to AST and back and the result compiles with gfortran and SNAP gives identical results. This ensures that there are no major bugs in the parser and the AST representation (there might still be some minor bugs where we got the right result by accident). Here are all the files sorted from the largest to the smallest:

* [x] setup.f90
* [x] thrd_comm.f90
* [x] input.f90
  * [x] read (https://gitlab.com/lfortran/lfortran/-/merge_requests/821)
  * [x] namelist declaration (https://gitlab.com/lfortran/lfortran/-/merge_requests/835)
* [x] mms.f90
* [x] mkba_sweep.f90
* [x] dim3_sweep.f90
  * [x] `continue` (https://gitlab.com/lfortran/lfortran/-/merge_requests/836)
* [x] translv.f90
  * [x] `use` inside subroutine (https://gitlab.com/lfortran/lfortran/-/merge_requests/828, https://gitlab.com/lfortran/lfortran/-/merge_requests/831)
  * [x] implied do loop (https://gitlab.com/lfortran/lfortran/-/merge_requests/832)
* [x] output.f90
* [x] outer.f90
* [x] inner.f90
  * [x] write/format
* [x] sweep.f90
* [x] plib.f90
  * [x] interface (https://gitlab.com/lfortran/lfortran/-/merge_requests/808)
* [x] solvar.f90
  * [x] allocate/deallocate (https://gitlab.com/lfortran/lfortran/-/merge_requests/807)
* [x] geom.f90
  * [x] derived type in fmt (https://gitlab.com/lfortran/lfortran/-/merge_requests/825)
  * [x] derived type access in expressions (https://gitlab.com/lfortran/lfortran/-/merge_requests/826)
* [x] snap_main.f90
  * [x] write/format
* [x] dim1_sweep.f90
* [x] utils.f90
  * [x] strings `'aa' // 'bb'` incorrectly printed (https://gitlab.com/lfortran/lfortran/-/merge_requests/808)
  * [x] write
  * [x] open (https://gitlab.com/lfortran/lfortran/-/merge_requests/824)
  * [x] close (https://gitlab.com/lfortran/lfortran/-/merge_requests/823)
* [x] octsweep.f90
* [x] sn.f90
  * [x] allocate/deallocate (https://gitlab.com/lfortran/lfortran/-/merge_requests/807)
* [x] data.f90
  * [x] allocate/deallocate (https://gitlab.com/lfortran/lfortran/-/merge_requests/807)
* [x] control.f90
  * [x] allocate/deallocate statements (https://gitlab.com/lfortran/lfortran/-/merge_requests/807)
* [x] time.f90
  * [x] write/format
* [x] expxs.f90
  * [x] interface (https://gitlab.com/lfortran/lfortran/-/merge_requests/808)
* [x] analyze.f90
  * [x] Dimension missing arguments (https://gitlab.com/lfortran/lfortran/-/merge_requests/806)
* [x] version.f90
  * [x] `write` prints as `print` (https://gitlab.com/lfortran/lfortran/-/merge_requests/814, https://gitlab.com/lfortran/lfortran/-/merge_requests/815, https://gitlab.com/lfortran/lfortran/-/merge_requests/820, https://gitlab.com/lfortran/lfortran/-/merge_requests/822)
  * [x] `format` statements are skipped (https://gitlab.com/lfortran/lfortran/-/merge_requests/809, https://gitlab.com/lfortran/lfortran/-/merge_requests/811, https://gitlab.com/lfortran/lfortran/-/merge_requests/812, https://gitlab.com/lfortran/lfortran/-/merge_requests/813)
* [x] dealloc.f90
* [x] global.f90

## ASR

The goal is to compile each module to the modfile using `lfortran -c global.f90 -o global.o`. Here is the first full dependency tree, we can take it from top to bottom:

* [x] global.f90
  * [x] Module `save` attribute (https://gitlab.com/lfortran/lfortran/-/merge_requests/884)
  * [x] Intrinsic `kind` function, `SELECTED_INT_KIND` and `SELECTED_REAL_KIND` (https://gitlab.com/lfortran/lfortran/-/merge_requests/885, https://gitlab.com/lfortran/lfortran/-/merge_requests/888, https://gitlab.com/lfortran/lfortran/-/merge_requests/900) 
* [x] version.o : global.o
  * [x] Issues with loading the `global` module (https://gitlab.com/lfortran/lfortran/-/merge_requests/901, https://gitlab.com/lfortran/lfortran/-/merge_requests/902, https://gitlab.com/lfortran/lfortran/-/merge_requests/903, https://gitlab.com/lfortran/lfortran/-/merge_requests/904)
  * [x] Allow to use module variables in `use` (https://gitlab.com/lfortran/lfortran/-/merge_requests/906)
  * [ ] Intrinsic subroutine `DATE_AND_TIME`
  * [ ] Intrinsic `write`
* [x] geom.o :    global.o
* [x] sn.o :      global.o
  * [x] `allocatable` attribute for array declarations (module variable)
* [x] data.o :    global.o
* [x] control.o : global.o
* [x] time.o :    global.o
* [x] plib.o :    global.o time.o
* [x] thrd_comm.o:    global.o plib.o
* [x] expxs.o :   global.o geom.o sn.o data.o
* [x] solvar.o :  global.o plib.o geom.o sn.o data.o control.o
* [x] mms.o:      global.o geom.o sn.o data.o control.o plib.o
  * [x] Generic procedures from the plib module (https://gitlab.com/lfortran/lfortran/-/issues/358)
  * [ ] "LFortranException: read_string: String is too short for deserialization", probably due to derived types
* [x] dealloc.o : global.o sn.o data.o mms.o geom.o solvar.o control.o
* [x] utils.o :   global.o dealloc.o plib.o control.o
* [x] analyze.o:  global.o control.o geom.o data.o solvar.o plib.o
* [x] input.o :   global.o plib.o geom.o sn.o data.o control.o utils.o time.o
* [x] setup.o :   global.o geom.o sn.o data.o control.o mms.o utils.o time.o plib.o
* [x] output.o :  global.o geom.o sn.o data.o control.o utils.o solvar.o mms.o time.o plib.o
* [x] snap_main.o :   global.o utils.o version.o input.o setup.o output.o time.o dealloc.o plib.o control.o
* [x] dim1_sweep.o :  global.o geom.o sn.o data.o control.o plib.o
* [x] dim3_sweep.o :  global.o plib.o geom.o sn.o data.o control.o thrd_comm.o
* [x] mkba_sweep.o :  global.o plib.o geom.o sn.o data.o control.o thrd_comm.o
* [x] octsweep.o :    global.o geom.o sn.o data.o control.o solvar.o thrd_comm.o dim1_sweep.o dim3_sweep.o mkba_sweep.o
* [x] sweep.o :   global.o data.o geom.o sn.o control.o octsweep.o solvar.o plib.o thrd_comm.o
* [x] inner.o :   global.o geom.o sn.o data.o control.o solvar.o sweep.o time.o plib.o thrd_comm.o
* [x] outer.o :   global.o geom.o sn.o data.o solvar.o control.o inner.o time.o plib.o expxs.o thrd_comm.o
* [x] translv.o : global.o plib.o geom.o sn.o data.o control.o utils.o solvar.o expxs.o outer.o time.o thrd_comm.o analyze.o

Other issues to resolve:

* [x] Runtime library must be working

The LFortran and SNAP commits that together produce an ASR for `snap_main.f90`:

* The latest master of LFortran (as of 93d2b868d986dbf7013ff4a811303b28f17fb126)
* https://github.com/certik/SNAP/commit/c10d86d3c7970c0ff070360496797132fac0462f

Fortran features that were commented out in SNAP that we need to implement in LFortran:

* [ ] format statement
* [ ] do loops with no loop variable (just `do` / code / `end do`)
* [ ] where statement
* [ ] improve derived types: we have an initial implementation, but we need to improve it for SNAP
* [ ] namelist
* [ ] array initializer
* [ ] case statement for strings
* [ ] improve pointers: add nullify, fix bugs
* [ ] improve open statement
* [ ] runtime library functions: huge, all, mod, minloc, ceiling, maxloc, get_command_argument, adjustl, exit, date_and_time

The SNAP branch compiles with gfortran into an executable, and runs with an output:
```console
$ ./gsnap 
 Aww SNAP. Program failed. Try again.
```
The parts that were commented out make the code not run correctly, but it "runs".

### C++

The C++ backend (as of the latest master 93d2b868d986dbf7013ff4a811303b28f17fb126) generates the following code:

* https://gist.github.com/certik/bbfbffd6a247adb22f2fb9bc3d7b3a77

It does not compile with a C++ compiler yet. This is our main effort now.

## Other issues

* [x] Figure out how to run a simple example without MPI: https://github.com/lanl/SNAP/issues/12, so that we can compare results against other Fortran compilers.
