### ISSUE TITLE
Roadmap to compile `dftatom`

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#320]
*Original issue*: https://gitlab.com/lfortran/lfortran/-/issues/319

Here is a roadmap for `dftatom`: https://github.com/certik/dftatom

Similar to https://gitlab.com/lfortran/lfortran/-/issues/313, this issue is to keep track of things to fix to get LFortran to compile dftatom. In terms of MVP, the SNAP project (https://gitlab.com/lfortran/lfortran/-/issues/313) is sufficient, this issue is beyond MVP.

# Parser

It seems to parse.

# AST

Everything parses to AST and back to source code and it seems to produce identical results when compiled with gfortran (all tests pass).

One can apply the src -> AST -> src transformation as follows:
```
cd src
find . -name "*.f90" -exec lfortran fmt -i {} \;
```
Make sure to enable long lines:
```diff
--- a/cmake/UserOverride.cmake
+++ b/cmake/UserOverride.cmake
@@ -7,7 +7,7 @@
 # variables.
 if (CMAKE_Fortran_COMPILER_ID STREQUAL "GNU")
     # gfortran
-    set(common "-std=f2003 -Wall -Wextra -Wimplicit-interface -fPIC -fmax-errors=1")
+    set(common "-std=f2003 -ffree-line-length-none -Wall -Wextra -Wimplicit-interface -fPIC -fmax-errors=1")
     set(CMAKE_Fortran_FLAGS_RELEASE_INIT "${common} -O3 -march=native -ffast-math -funroll-loops")
     set(CMAKE_Fortran_FLAGS_DEBUG_INIT   "${common} -g -fbounds-check -fcheck-array-temporaries -fbacktrace")
 elseif (CMAKE_Fortran_COMPILER_ID STREQUAL "Intel")
```

Issues:

* [x] pure attribute in functions / subroutines not preserved (https://gitlab.com/lfortran/lfortran/-/merge_requests/839)
* [x] recursive attribute in functions / subroutines not preserved (https://gitlab.com/lfortran/lfortran/-/merge_requests/839)
* [x] `real(dp)` kind not preserved in function results (https://gitlab.com/lfortran/lfortran/-/merge_requests/839)
* [x] `bind(C)` (https://gitlab.com/lfortran/lfortran/-/merge_requests/853)
* [x] `inquire` (https://gitlab.com/lfortran/lfortran/-/merge_requests/847)
* [x] `import` (https://gitlab.com/lfortran/lfortran/-/merge_requests/855, https://gitlab.com/lfortran/lfortran/-/merge_requests/856)
* [x] `a(*)` vs `a(:)` (https://gitlab.com/lfortran/lfortran/-/merge_requests/857)
* [x] `backspace` (https://gitlab.com/lfortran/lfortran/-/merge_requests/859)
* [x] Parse more implicit statements (https://gitlab.com/lfortran/lfortran/-/merge_requests/860)
* [x] Dimension without arguments (https://gitlab.com/lfortran/lfortran/-/merge_requests/861)
* [x] Escape strings (https://gitlab.com/lfortran/lfortran/-/merge_requests/863)
* [x] `go to` (https://gitlab.com/lfortran/lfortran/-/merge_requests/864, https://gitlab.com/lfortran/lfortran/-/merge_requests/868)
* [x] `do 15 i=1,15` (https://gitlab.com/lfortran/lfortran/-/merge_requests/866)
* [x] fmt: different implicit statements (https://gitlab.com/lfortran/lfortran/-/merge_requests/875)
* [x] AST/fmt: labels in front of statements (https://gitlab.com/lfortran/lfortran/-/merge_requests/865, https://gitlab.com/lfortran/lfortran/-/merge_requests/871, https://gitlab.com/lfortran/lfortran/-/merge_requests/877, https://gitlab.com/lfortran/lfortran/-/merge_requests/869, https://gitlab.com/lfortran/lfortran/-/merge_requests/880, https://gitlab.com/lfortran/lfortran/-/merge_requests/882, https://gitlab.com/lfortran/lfortran/-/merge_requests/881)

# ASR
This follows the same logic as https://gitlab.com/lfortran/lfortran/-/issues/313. Compile each module with `lfortran -c blah.f90 -o blah.o` and write out (manually) a dependency tree. A task made much easier with `fortdepend`.
* [x] types.o
* [x] lapack.o -- https://gitlab.com/lfortran/lfortran/-/merge_requests/997
* [ ] utils.o :	types.o -- https://gitlab.com/lfortran/lfortran/-/issues/374 
* [x] constants.o :	types.o
* [x] dft_data.o : 	types.o
* [ ] mesh.o : -- https://gitlab.com/lfortran/lfortran/-/issues/388
  * [ ] types.o
  * [ ] utils.o
* [x] states.o : -- https://gitlab.com/lfortran/lfortran/-/issues/389
  * [x] types.o
  * [ ] utils.o
* [ ] ode1d.o : -- https://gitlab.com/lfortran/lfortran/-/issues/390 
  * [ ] types.o
  * [ ] utils.o
* [ ] energies.o :
  * [ ] constants.o
  * [ ] types.o
  * [ ] utils.o
* [ ] interpolation.o :
  * [ ] lapack.o
  * [ ] types.o
  * [ ] utils.o
* [ ] rschroed.o :
  * [ ] ode1d.o
  * [ ] types.o
  * [ ] utils.o
* [ ] rdirac.o :
  * [ ] ode1d.o
  * [ ] types.o
  * [ ] utils.o
* [ ] rpoisson.o :
  * [ ] constants.o
  * [ ] ode1d.o
  * [ ] types.o
  * [ ] utils.o
* [ ] ode1d_other.o :
  * [ ] constants.o
  * [ ] ode1d.o
  * [ ] types.o
  * [ ] utils.o
* [ ] rschroed_other.o :
  * [ ] ode1d.o
  * [ ] ode1d_other.o
  * [ ] types.o
  * [ ] utils.o
* [ ] rdirac_other.o :
  * [ ] ode1d.o
  * [ ] ode1d_other.o
  * [ ] types.o
  * [ ] utils.o
* [ ] rpoisson_other.o :
  * [ ] constants.o
  * [ ] ode1d.o
  * [ ] ode1d_other.o
  * [ ] types.o
* [ ] reigen.o :
  * [ ] ode1d.o
  * [ ] rdirac.o
  * [ ] rschroed.o
  * [ ] types.o
  * [ ] utils.o
* [ ] mixings.o :
  * [ ] constants.o
  * [ ] dft_data.o
  * [ ] ode1d.o
  * [ ] types.o
  * [ ] utils.o
* [ ] dft.o :
  * [ ] constants.o
  * [ ] dft_data.o
  * [ ] energies.o
  * [ ] mixings.o
  * [ ] ode1d.o
  * [ ] reigen.o
  * [ ] rpoisson.o
  * [ ] types.o
  * [ ] utils.o
* [ ] drivers.o :
  * [ ] constants.o
  * [ ] dft.o
  * [ ] dft_data.o
  * [ ] energies.o
  * [ ] mesh.o
  * [ ] mixings.o
  * [ ] ode1d.o
  * [ ] states.o
  * [ ] types.o
* [ ] dftatom.o :
  * [ ] dft.o
  * [ ] drivers.o
  * [ ] energies.o
  * [ ] mesh.o
  * [ ] ode1d.o
  * [ ] reigen.o
  * [ ] rpoisson.o
  * [ ] states.o
  * [ ] types.o
  * [ ] utils.o
* [ ] c_dftatom.o :
  * [ ] dft.o
  * [ ] dft_data.o
  * [ ] dftatom.o
  * [ ] mixings.o
# Backends

## C++

**Comment by certik** [comment]
dftatom now compiles and works.
