### ISSUE TITLE
Stdlib: Strings master issue

### ISSUE THREAD

**Issue by Shaikh-Ubaid** [lfortran/lfortran#3503]
- [ ] https://github.com/lfortran/lfortran/issues/3487
- [ ] https://github.com/lfortran/lfortran/issues/3494
- [ ] https://github.com/lfortran/lfortran/issues/3498
- [ ] https://github.com/lfortran/lfortran/issues/3499
- [ ] https://github.com/lfortran/lfortran/issues/3500
- [ ] https://github.com/lfortran/lfortran/issues/3501 (https://github.com/lfortran/lfortran/pull/3502)

**Comment by gxyd** [comment]
@Shaikh-Ubaid , could you check if the issue https://github.com/lfortran/lfortran/issues/3545#issuecomment-1966532106 is listed above already?

**Comment by Shaikh-Ubaid** [comment]
>could you check if the issue https://github.com/lfortran/lfortran/issues/3545#issuecomment-1966532106 is listed above already?

I think it is not listed here. This issue is especially tracks `stdlib-strings` related issues.

**Comment by gxyd** [comment]
Isn't the below issue relevant for stdlib-strings?
```bash
> cat a.f90
program main
    character(8) :: s
    s = "lfortran"
    print *, s(-1:3)
end program

> lfortran a.f90
                          <- empty string

> echo $?
0
```

**Comment by Shaikh-Ubaid** [comment]
>Isn't the below issue relevant for stdlib-strings?

I did not notice/experience it while supporting the stdlib strings tests yet. But I think it is a good issue for LFortran and it should be fixed.
