### ISSUE TITLE
`minidftatom` Roadmap

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#354]
*Original issue*: https://gitlab.com/lfortran/lfortran/-/issues/401

Here is a roadmap for `minidftatom`: https://gitlab.com/lfortran/examples/minidftatom

A restricted subset to explore AST->ASR issues and fixes.

# Parser

Tested implicitly by the AST transform.

# AST

Everything parses to AST and back to source code and it seems to produce identical results when compiled with gfortran (all tests pass).

One can apply the src -> AST -> src transformation as follows:
```bash
cd minidftatom
# -i --> Inplace modification
for file in *.f90; do lfortran fmt -i $file; done
```
Make sure to enable long lines with `-ffree-line-length-none`.
# ASR
This follows the same logic as https://gitlab.com/lfortran/lfortran/-/issues/313. Compile each module with `lfortran -c blah.f90 -o blah.o` and write out (manually) a dependency tree. A task made much easier with `fortdepend`.
* [x] types.o
* [x] constants.o
	* [x] types.o
* [x] states.o
	* [x] types.o
* [x] mesh.o -- https://gitlab.com/lfortran/lfortran/-/issues/388 
	* [x] types.o
* [x] dft_data.o
	* [x] types.o
* [x] ode1d.o -- ~~https://gitlab.com/lfortran/lfortran/-/issues/400 :: Actually need to handle `g(size(Rp))`~~ https://gitlab.com/lfortran/lfortran/-/issues/468 
	* [x] types.o
* [x] energies.o -- ~~https://gitlab.com/lfortran/lfortran/-/issues/400 (need `real :: E(size(x))`)~~ https://gitlab.com/lfortran/lfortran/-/issues/468 https://gitlab.com/lfortran/lfortran/-/issues/475 https://gitlab.com/lfortran/lfortran/-/issues/476 https://gitlab.com/lfortran/lfortran/-/issues/477
	* [x] constants.o 
	* [x] types.o
* [ ] mixings.o
	* [x] constants.o 
	* [x] dft_data.o 
	* [x] ode1d.o 
	* [x] types.o
* [ ] rschroed.o
	* [ ] ode1d.o 
	* [x] types.o
* [ ] rpoisson.o
	* [ ] constants.o 
	* [ ] ode1d.o 
	* [ ] types.o
* [ ] reigen.o
	* [ ] ode1d.o 
	* [ ] rschroed.o 
	* [ ] types.o
* [ ] dft.o
	* [x] constants.o 
	* [x] dft_data.o 
	* [ ] energies.o 
	* [ ] mixings.o 
	* [ ] ode1d.o 
	* [ ] reigen.o 
	* [ ] rpoisson.o 
	* [ ] types.o
* [ ] drivers.o
	* [ ] dft.o 
	* [ ] dft_data.o 
	* [ ] energies.o 
	* [ ] mesh.o 
	* [ ] mixings.o 
	* [ ] states.o 
	* [ ] types.o
* [ ] F_atom_U.o
	* [ ] drivers.o 
	* [ ] types.o
* [ ] atom_U
	* [ ] F_atom_U.o 
	* [ ] constants.o 
	* [ ] dft.o 
	* [ ] dft_data.o 
	* [ ] drivers.o 
	* [ ] energies.o 
	* [ ] mesh.o 
	* [ ] mixings.o 
	* [ ] ode1d.o 
	* [ ] reigen.o 
	* [ ] rpoisson.o 
	* [ ] rschroed.o 
	* [ ] states.o 
	* [ ] types.o

# Backends

## LLVM

...
