### ISSUE TITLE
Optimizations list

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#358]
*Original issue*: https://gitlab.com/lfortran/lfortran/-/issues/427

Here are some ideas for ASR->ASR optimizations optional passes that we should implement:

* [ ] compile time evaluation
* [ ] function inlining
* [ ] loop unrolling (if the size is known)
* [ ] if and select case statement evaluation (dead code elimination)
* [ ] efficient array evaluations (https://gitlab.com/lfortran/lfortran/-/issues/383), in particular: 
  * [ ] Efficient `1/sqrt(x)` implementation that vectorizes well (needed for https://gitlab.com/lfortran/lfortran/-/issues/647)
  * [ ] Efficient `sum(r(:,m)**2)` implementation the vectorizes well (needed for https://gitlab.com/lfortran/lfortran/-/issues/647)
  * [ ] `maxval(abs(a-b))`
  * [ ] `sqrt(dot_product(array,array))`
* [ ] https://gitlab.com/lfortran/lfortran/-/issues/428: loop vectorization with user or intrinsic functions such as `sin(A(i))` --- even if it is called as a scalar, by tiling the loop `sin(A(a:b))` could be changed to evaluate for a vector. The same for user defined generic procedures.
* [ ] Efficient functions returning arrays (rewrite as subroutines)
* [ ] Eliminate allocatable arrays when possible: both inside subroutines and `intent(out), allocatable` (requires to ensure the caller provides an array of the correct size, properly allocated: by moving up the allocatable statement from the subroutine into the caller, so the subroutine is allocatable free, it just uses automatic array; then one follows the same procedure in the caller to eliminate allocatable if possible)
* [ ] labeled per block optimizations (https://gitlab.com/lfortran/lfortran/-/issues/551)
* [ ] Floating point optimizaitons:
  * [ ] `if (modulo(number, 2) == 1 ) x = -x` (https://gitlab.com/lfortran/lfortran/-/merge_requests/1612)
  * [ ] `0.5_dp*sign(1._dp, x)` (https://gitlab.com/lfortran/lfortran/-/issues/651)
  * [ ] `x/pi -> x*(1/pi)` (https://gitlab.com/lfortran/lfortran/-/issues/650)
  * [ ] fma (https://gitlab.com/lfortran/lfortran/-/issues/649)
  * [ ] `if (x>=0) then; r=x; else r=x-1; end if` -> `r = x-(x>>63)` (https://gitlab.com/lfortran/lfortran/-/issues/697)

For reference, here is a list of optimization passes that LLVM can do:

* https://llvm.org/docs/Passes.html#transform-passes
