### ISSUE TITLE
TODO for beta

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#3806]
In order to reach beta quality, we need to implement the following items:

* [ ] All instrinsic functions working (compile time, runtime): @HarshitaKalani, @parth121101
* [ ] array_op redesign: @czgdp1807 
* [ ] https://github.com/lfortran/lfortran/issues/2257: @Shaikh-Ubaid 
* [ ] https://github.com/lfortran/lfortran/issues/3581: @Pranavchiku 
* [ ] robust deallocation (https://github.com/lfortran/lfortran/issues/3770)
* [ ] most OOP features
* [ ] `--fast` working in all cases
* [ ] compile at least 10 codes without any workaround (except the items listed below)

After we reach beta, we will tackle the following:

* coarrays
* submodules
* common block and other F77 features that should not be used in new codes (but we have to support to compile old codes)
* separate compilation (generate intermediate object files, link everything at the end)
* Other backends (WASM, C, C++)

**Comment by thoth291** [comment]
I think that it would be better not to wait for everything to be done to make it work with Jupyter kernel. I can see how it can be useful to have a testing repo with Binder and Colab integration. That would help anyone to test recent version and report back issues if any discovered.

**Comment by certik** [comment]
@thoth291 the Jupyter kernel already works. The above issue is to focus on ironic all bugs there, which we should do after we can compile standalone codes (i.e., after beta). If you discover a bug in the kernel, go ahead and report it, we fix them as we have time.

**Comment by krystophny** [comment]
| Status | Track | Issues | PRs |
|---|---|---|---|
| needs review | ASR docs | [#7006](https://github.com/lfortran/lfortran/issues/7006) | [#9808](https://github.com/lfortran/lfortran/pull/9808) |
| needs review | M_framework | [#10885](https://github.com/lfortran/lfortran/issues/10885) | [#11796](https://github.com/lfortran/lfortran/pull/11796) |
| needs completion | Warnings | [#10605](https://github.com/lfortran/lfortran/issues/10605) | [#10696](https://github.com/lfortran/lfortran/pull/10696) |
| needs completion | Compiler options | [#7937](https://github.com/lfortran/lfortran/issues/7937) | [#8105](https://github.com/lfortran/lfortran/pull/8105) |
| needs completion | Function flags | [lpython#1266](https://github.com/lcompilers/lpython/issues/1266) | [lpython#1293](https://github.com/lcompilers/lpython/pull/1293), [#7710](https://github.com/lfortran/lfortran/pull/7710) |
| needs completion | M_strings | [#10884](https://github.com/lfortran/lfortran/issues/10884) | [#11065](https://github.com/lfortran/lfortran/pull/11065) |
| needs completion | Netlib | [#11090](https://github.com/lfortran/lfortran/issues/11090), [#11111](https://github.com/lfortran/lfortran/issues/11111), [#12208](https://github.com/lfortran/lfortran/issues/12208) | [#11593](https://github.com/lfortran/lfortran/pull/11593) |
| needs completion | ASR docs old draft | [#7006](https://github.com/lfortran/lfortran/issues/7006) | [#8052](https://github.com/lfortran/lfortran/pull/8052) |
| wip | M_intrinsics | [#10888](https://github.com/lfortran/lfortran/issues/10888) | — |
| wip | Code backlog (39) | [label](https://github.com/lfortran/lfortran/labels/Code%20to%20be%20Compiled) | — |
| assigned | Bounds tracker | [#8306](https://github.com/lfortran/lfortran/issues/8306) | — |
| open | Bounds diagnostics | [#8307](https://github.com/lfortran/lfortran/issues/8307) | — |
| open | ClassToStruct | [#9950](https://github.com/lfortran/lfortran/issues/9950) | — |
| open | Pointer checks | [#338](https://github.com/lfortran/lfortran/issues/338), [#341](https://github.com/lfortran/lfortran/issues/341), [#5382](https://github.com/lfortran/lfortran/issues/5382), [#7838](https://github.com/lfortran/lfortran/issues/7838) | — |
| open | ttype caching | [#8161](https://github.com/lfortran/lfortran/issues/8161), [#8172](https://github.com/lfortran/lfortran/issues/8172) | — |
| open | featom | [#10980](https://github.com/lfortran/lfortran/issues/10980) | — |
