### ISSUE TITLE
A list of convenience issues to fix

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#384]
*Original issue*: https://gitlab.com/lfortran/lfortran/-/issues/497

These are not a high priority, but something that I would like to see fixed.

* [ ] https://gitlab.com/lfortran/lfortran/-/issues/498: Print an error message with line numbers for `--show-asr`. Unify the error reporting.
* [ ] Make --show-stacktrace work with every option such as `show-llvm`
* [x] Do not show the intrinsic libraries in ASR tests (so that when we add or change them, the hundreds of tests do not change) (https://gitlab.com/lfortran/lfortran/-/merge_requests/1181)
* [ ] Refactor ASR passes (https://gitlab.com/lfortran/lfortran/-/issues/552)
* [ ] Better `--show-asr --indent`, print it more line by line (https://gitlab.com/lfortran/lfortran/-/issues/426)
* [ ] ASR to AST (and SRC), and creating an ASR diff after a pass
* [ ] Fix up the location information (use linear info, convert. Assign with prescanner)
* [ ] html based AST and ASR browser, with information like names of the fields when clicked. To learn and to debug.
* [ ] Replace old style casts with `down_cast` in `asr_to_llvm`
* [ ] make all intrinsic module names as `[@ intrinsic](https://gitlab.com/intrinsic)[@ math2](https://gitlab.com/math2)` and write a function that determines if ASR::Module_t is intrinsic (true/false)
