### ISSUE TITLE
TODO for sin implementation

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#390]
*Original issue*: https://gitlab.com/lfortran/lfortran/-/issues/511

* [ ] fix LLVM order of function compilation (then remove the `a6` prefix)
* [ ] make abs, floor, modulo, min, max regular intrinsic functions (as opposed to local functions in the math2.f90 module)
* [ ] explore more accurate reduction algorithm for larger arguments `x`

More TODO: https://gitlab.com/lfortran/lfortran/-/merge_requests/1196#note_651076576
