### ISSUE TITLE
Compiling SciPy's stats/statlib

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#439]
Current Status:

- [x] AST to ASR
- [ ] ASR to LLVM

-----

*Original issue*: https://gitlab.com/lfortran/lfortran/-/issues/581

[There are](https://github.com/scipy/scipy/tree/a6124626bb99d73aa7f99bf8e3da7d9e2c670aa8/scipy/stats/statlib) just three relatively small files. See https://gitlab.com/lfortran/lfortran/-/issues/582 for compiling all of SciPy.

### ansari.f

```diff
--- a/scipy/stats/statlib/ansari.f
+++ b/scipy/stats/statlib/ansari.f
@@ -18,7 +18,7 @@ C       CHECK PROBLEM SIZE AND DEFINE BASE VALUE OF THE DISTRIBUTION.
 C
       M = MIN0(TEST, OTHER)
       IFAULT = 2
-      IF (M. LT. 0) RETURN
+      IF (M .LT. 0) RETURN
       ASTART = FPOINT((TEST + 1) / 2) * FPOINT(1 + TEST / 2)
       N = MAX0(TEST, OTHER)
 C
```
Then it parses:
```console
$ lfortran --show-ast --fixed-form ansari.f
```

ASR: 

* [x] We need implicit typing (https://gitlab.com/lfortran/lfortran/-/issues/737).
* [x] data statement (`DATA ONE /1.0/`)
* [ ] arithmetic if (`IF (MM1) 1, 2, 3`)
* [ ] `min0`, `max0` intrinsic functions missing
* [ ] statement functions (`FPOINT(I) = I`)

LLVM:

* [x] https://gitlab.com/lfortran/lfortran/-/issues/748

By commenting out the above unimplemented ASR features, it compiles to LLVM!

For use with SciPy:

* [x] we must generate an object file from this LLVM code (https://gitlab.com/lfortran/lfortran/-/issues/749)
* [ ] we must link multiple object files together with the runtime library correctly (https://gitlab.com/lfortran/lfortran/-/issues/751)
* [ ] the ABI must be the same as with GFortran, e.g., this `define void [@ frqadd](https://gitlab.com/frqadd)(%array* %f1, i32* %l1in, i32* %l1out, i32* %l1, %array* %f2, i32* %l2, i32* %nstart)` must be the same (it looks like `%array*` is a double pointer to data, while GFortran would use a single pointer)

### spearman.f

It parses:
```
lfortran --fixed-form --show-ast spearman.f
```
For ASR, we need to implement `data`, sole `dimension` attribute, `double precision` function return value, and implicit typing. For now we can workaround with:
```diff
--- a/scipy/stats/statlib/spearman.f
+++ b/scipy/stats/statlib/spearman.f
@@ -1,4 +1,4 @@
-      double precision function prho(n, is, ifault)
+      real(8) function prho(n, is, ifault)
 c
 c        Algorithm AS 89   Appl. Statist. (1975) Vol.24, No. 3, P377.
 c       
@@ -8,14 +8,17 @@ c        must be greater than 1
 c
 c     Auxiliary function required: ALNORM = algorithm AS66
 c
-      dimension l(6)
-      double precision zero, one, two, b, x, y, z, u, six,
-     $  c1, c2, c3, c4, c5, c6, c7, c8, c9, c10, c11, c12
-      data zero, one, two, six /0.0d0, 1.0d0, 2.0d0, 6.0d0/
-      data        c1,     c2,     c3,     c4,     c5,     c6,
-     $          c7,     c8,     c9,    c10,    c11,    c12/
-     $  0.2274d0, 0.2531d0, 0.1745d0, 0.0758d0, 0.1033d0, 0.3932d0,
-     $  0.0879d0, 0.0151d0, 0.0072d0, 0.0831d0, 0.0131d0, 0.00046d0/
+      integer, intent(in) :: n, is
+      integer, intent(out) :: ifault
+      integer :: l(6)
+      double precision b, x, y, z, u
+      double precision, parameter :: zero = 0.0d0, one=1.0d0,
+     $    two=2.0d0, six=6.0d0
+      double precision, parameter :: c1=0.2274d0, c2 =0.2531d0,
+     $  c3 =0.1745d0, c4 =0.0758d0, c5 =0.1033d0, c6 =0.3932d0,
+     $  c7 =0.0879d0, c8 =0.0151d0, c9 =0.0072d0, c10=0.0831d0,
+     $  c11=0.0131d0, c12=0.00046d0
+      integer :: js
 c
 c        Test admissibility of arguments and initialize
 c
```
Then it fails with:
```
$ lfortran --fixed-form -c spearman.f -o a.o
Traceback (most recent call last):
  File "/Users/certik/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 1425
    return compile_to_object_file(arg_file, outfile, platform, false,
  File "/Users/certik/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 692
    if (result.ok) {
  File "/Users/certik/repos/lfortran/lfortran/src/lfortran/codegen/fortran_evaluator.cpp", line 250
    asr = ast_to_asr(al, *ast, symbol_table);
  File "/Users/certik/repos/lfortran/lfortran/src/lfortran/semantics/ast_to_asr.cpp", line 36
    ASR::TranslationUnit_t *tu = body_visitor(al, ast, unit);
  File "/Users/certik/repos/lfortran/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 2160
    b.visit_TranslationUnit(ast);
  File "/Users/certik/repos/lfortran/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 89
    visit_ast(*x.m_items[i]);
  File "/Users/certik/repos/lfortran/lfortran/src/lfortran/ast.h", line 4572
    void visit_ast(const ast_t &b) { visit_ast_t(b, self()); }
  File "/Users/certik/repos/lfortran/lfortran/src/lfortran/ast.h", line 4532
    case astType::program_unit: { v.visit_program_unit((const program_unit_t &)x); return; }
  File "/Users/certik/repos/lfortran/lfortran/src/lfortran/ast.h", line 4580
    void visit_program_unit(const program_unit_t &b) { visit_program_unit_t(b, self()); }
  File "/Users/certik/repos/lfortran/lfortran/src/lfortran/ast.h", line 4198
    case program_unitType::Function: { v.visit_Function((const Function_t &)x); return; }
  File "/Users/certik/repos/lfortran/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 778
    this->visit_stmt(*x.m_body[i]);
  File "/Users/certik/repos/lfortran/lfortran/src/lfortran/ast.h", line 4613
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/Users/certik/repos/lfortran/lfortran/src/lfortran/ast.h", line 4324
    case stmtType::If: { v.visit_If((const If_t &)x); return; }
  File "/Users/certik/repos/lfortran/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 1950
    visit_stmt(*x.m_body[i]);
  File "/Users/certik/repos/lfortran/lfortran/src/lfortran/ast.h", line 4613
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/Users/certik/repos/lfortran/lfortran/src/lfortran/ast.h", line 4302
    case stmtType::GoTo: { v.visit_GoTo((const GoTo_t &)x); return; }
  File "/Users/certik/repos/lfortran/lfortran/src/lfortran/ast.h", line 4633
    void visit_GoTo(const GoTo_t & /* x */) { throw LFortran::LFortranException("visit_GoTo() not implemented"); }
LFortranException: visit_GoTo() not implemented
```

We need to implement goto in AST->ASR.

Update: GoTo has been implemented.

### swilk.f

It parses:
```
$ lfortran --fixed-form --show-ast swilk.f
```

It seems the ASR failure is on `dimension :: l(6)`, "Attribute declaration not supported"

**Comment by certik** [comment]
This works:
```console
$ lfortran --show-asr --fixed-form --implicit-typing --implicit-interface ./scipy/stats/statlib/spearman.f
```
This does not yet:
```console
$ lfortran --show-asr --fixed-form --implicit-typing --implicit-interface ./scipy/stats/statlib/swilk.f 
ASR verify pass error: ASR verify: Function zexp depends on dexp but isn't found in its dependency list.
   --> ./scipy/stats/statlib/swilk.f:253:7
    |
253 |       ZEXP(Z) = DEXP(Z)
    |       ^^^^^^^^^^^^^^^^^ failed here
$ lfortran --show-asr --fixed-form --implicit-typing --implicit-interface ./scipy/stats/statlib/ansari.f  
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 1860
    return emit_asr(arg_file, lfortran_pass_manager,
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 612
    r = fe.get_asr2(input, lm, diagnostics);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/fortran_evaluator.cpp", line 248
    Result<ASR::TranslationUnit_t*> res2 = get_asr3(*ast, diagnostics);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/fortran_evaluator.cpp", line 270
    compiler_options.symtab_only, compiler_options);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/semantics/ast_to_asr.cpp", line 96
    auto res = body_visitor(al, ast, diagnostics, unit, compiler_options,
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 2461
    b.requirement_map = requirement_map;
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 116
    visit_ast(*x.m_items[i]);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/ast.h", line 4764
    void visit_ast(const ast_t &b) { visit_ast_t(b, self()); }
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/ast.h", line 4722
    case astType::mod: { v.visit_mod((const mod_t &)x); return; }
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/ast.h", line 4772
    void visit_program_unit(const program_unit_t &b) { visit_program_unit_t(b, self()); }
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/ast.h", line 4373
    case program_unitType::Subroutine: { v.visit_Subroutine((const Subroutine_t &)x); return; }
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 1337
    transform_stmts(body, x.n_body, x.m_body);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 92
    this->visit_stmt(*m_body[i]);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/ast.h", line 4809
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/ast.h", line 4465
    case stmtType::Assign: { v.visit_Assign((const Assign_t &)x); return; }
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 1606
    if (is_statement_function(x)) {
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/semantics/ast_body_visitor.cpp", line 1529
    current_scope->add_symbol(arg_name, ASR::down_cast<ASR::symbol_t>(arg_var));
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/asr_scopes.h", line 74
    LCOMPILERS_ASSERT(scope.find(name) == scope.end())
AssertFailed: scope.find(name) == scope.end()
```
