### ISSUE TITLE
Intrinsics TODO

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#4593]
* [ ] https://github.com/lfortran/lfortran/issues/4398
* [ ] https://github.com/lfortran/lfortran/issues/4591 (`program_01.f90`)
* [ ] `arrays_intrin_02.f90`
* [ ] `any_01.f90`

**Comment by Thirumalai-Shaktivel** [comment]
Are the tests failing in the main branch?

**Comment by HarshitaKalani** [comment]
Yes

**Comment by harperjf** [comment]
Another intrinsic that seems to need fixing is ```transfer```. I reported the problem in #3961.

**Comment by harperjf** [comment]
A problem that may or may not be in the intrinsic ```huge``` is #3906. I added a comment to it today. It did hit me in actual code.
So did #3917 where the trouble with ```execute_command_line``` arose in a subroutine. It did not arise when that intrinsic was called in this 2-line main program in a Linux system.
``` 
  call execute_command_line('whoami')
end program
```

**Comment by certik** [comment]
Another TODO:
* [ ] remove `runtime/builtin/lfortran_intrinsic_builtin.f90`
* [ ] remove `runtime/custom/lfortran_intrinsic_custom.f90`
* [ ] remove `runtime/impure/lfortran_intrinsic_math.f90`
* [ ] remove `runtime/pure/lfortran_intrinsic_string.f90`

What will stay:
```
lfortran_intrinsic_ieee_arithmetic.f90
lfortran_intrinsic_iso_c_binding.f90
lfortran_intrinsic_iso_fortran_env.f90
```
And I think that's it!

**Comment by harperjf** [comment]
Other things TODO are 
(1) implementing all standard-comforming Fortran statements 
(2) implementing everything that iso_fortran_env and ieee_arithmetic should provide  
(3) implementing all the edit descriptors valid in formats 
(4) improving error messages so that users can see which lines in their Fortran programs caused the trouble (I don't know how to get that info from hexadecimal local addresses in conda-root or libc.so.6 .) 
And one day (5) allowing more than 2 real kinds. All my other Fortran compilers have either 3 or 4.

**Comment by certik** [comment]
> Other things TODO are
> (1) implementing all standard-conforming Fortran statements

What are the ones that are missing? We should have a pretty good support for all Fortran statements. If you know some that we missed, let us know. This a separate issue from intrinsics.

> (2) implementing everything that iso_fortran_env and ieee_arithmetic should provide

Yes, good point. Here are our current implementations:

* https://github.com/lfortran/lfortran/blob/0f9527863424a172b0d0bc93c21c3649f7141ff5/src/runtime/pure/lfortran_intrinsic_iso_fortran_env.f90
* https://github.com/lfortran/lfortran/blob/0f9527863424a172b0d0bc93c21c3649f7141ff5/src/runtime/pure/lfortran_intrinsic_ieee_arithmetic.f90

Probably both might have some missing things. If you know some, go ahead and open up issues for those.

> (3) implementing all the edit descriptors valid in formats

That's a separate issue from intrinsics. Go ahead and open up issues for all missing features.

> (4) improving error messages so that users can see which lines in their Fortran programs caused the trouble (I don't know how to get that info from hexadecimal local addresses in conda-root or libc.so.6 .)

That's always a bug. The stacktrace that you are seeing is an internal compiler error (ICE). Instead, we always need to give a nice error message. In terms of priorities, we will focus on invalid code after we compile all valid code.

> And one day (5) allowing more than 2 real kinds. All my other Fortran compilers have either 3 or 4.

Yep, we definitely need bfloat16, quadruple precision, and probably float16 also. That's a separate issue from intrinsics.

**Comment by harperjf** [comment]
Problems with statements, omitting those that have been fixed or have already been flagged as bugs by someone not me: #3811, #3904, #3905, #3925, #3935, #3943, #3936, #3960, #4357, #4427, #4501, #4553,  #4564, #4572, #4640, #4647, #4675. 

Edit descriptors missing or misinterpreted:   'b' 'o' 'z' 'g' ':'  and some cases of 'ES' 'EN' 'E' #3813, #3818, #4692, #4730. 

I'll work on the IEEE and ISO stuff when I've seen what your website says.

**Comment by harperjf** [comment]
On IEEE: some of the functions are inquiry but the current implementation makes them all elemental. Also,
ieee_support_standard(x) is missing. It has 3 versions: x of type sp, dp and absent. So should all the other ieee_support_* functions, but I didn't see the 'x absent' case in the module.

**Comment by Pranavchiku** [comment]
Thanks for all the work on intrinsics @HarshitaKalani and @parth121101 ! The PR https://github.com/lfortran/lfortran/pull/4736 has all constants used in LAPACK. It compiles well.

**Comment by certik** [comment]
@harperjf awesome, thanks for reporting all these and listing them! Some of them are unrelated to intrinsics, but some of them are indeed bugs in intrinsics. We'll finish our initial implementation first and then we'll focus on these. Some of them might be relatively easy to fix for newcomers, so we'll try to distribute the work.

**Comment by harperjf** [comment]
I was wrong to say that the ieee_support_ functions should not be elemental. Their  arguments may be arrays or scalars, and so they must be elemental. I owe @HarshitaKalani an apology.

**Comment by harperjf** [comment]
The plot thickens on ieee_support. The Fortran 2023 standard says that the result of these functions shall be a scalar (see 17.11.52 for example) even if their argument is an array. I now think that lfortran needs amendment because an elemental function must return an array in that situation. This program shows why:
```
  use ieee_arithmetic, only: ieee_support_datatype
  real x(10)
  print *,ieee_support_datatype(x)
```
Output from lfortran 0.40.0:
```
 T    T    T    T    T    T    T    T    T    T
```
Output from gfortran, g95, ifort, ifx and AMD flang:
```
 T
```
except that flang put an extra space before the ```T```.

**Comment by certik** [comment]
Thanks @harperjf for debugging it. Indeed, it looks like these functions are not elemental, so we should fix it.

**Comment by jalvesz** [comment]
Hello guys,

I was wondering if you are planning on adding the GNU Standard functions for `getcwd` and `chdir` ? For reference, `gfortran`, `intel` and `flang` implement the same API for these ones:

* gfortran: 
https://gcc.gnu.org/onlinedocs/gfortran/CHDIR.html
https://gcc.gnu.org/onlinedocs/gfortran/GETCWD.html

* Intel : 
https://www.intel.com/content/www/us/en/docs/fortran-compiler/developer-guide-reference/2025-2/chdir.html
https://www.intel.com/content/www/us/en/docs/fortran-compiler/developer-guide-reference/2025-2/getcwd.html

* flang:
https://flang.llvm.org/docs/Intrinsics.html#non-standard-intrinsics-chdir
https://flang.llvm.org/docs/Intrinsics.html#non-standard-intrinsics-getcwd
