### ISSUE TITLE
LSP TODO

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#4808]
For the language server, we need two orthogonal things:

### LFortran side:

Write LFortran tests that accept source code, line + column as input, and output various results:
  * for tab completion return all available tab completions at this point
  * declaration lookup will lookup declaration at this point

We need to make this working for all incorrectly written Fortran codes, every time we fix something in our fault tolerant parsing / semantics, we need to add a test here.

An alternative design is to just return ASR for all (incorrect) Fortran code, return it as JSON to the fortls, and fortls itself will determine the completions and lookups. Even for this smaller design we still need thorough tests that return a usable ASR, and we need tests to ensure the ASR is usable, by actually doing the lookup or actually doing the tab completion and ensure the completion is correct. So from an engineering perspective, we need to have tests in LFortran itself for all supported LSP features, to ensure ASR actually has the correct information. The LSP then has a choice, either implementing the lookups itself, or let LFortran do it.

### Integration side

We take the functionality from the previous point, and hook it into https://github.com/openlawlibrary/pygls, and get it working with VSCode via https://github.com/fortran-lang/fortls/. In here at first we need to get something working as a prototype, not a full design yet. We need this to ensure that all the pieces are working, and to exercise the previous point, which will be most of our effort. As we gain experience what features we need to support and how this all works, we will iterate on a design. We will figure out if LFortran should do the lookups, or LSP should do the lookups (or maybe we need both).

I recommend starting with LFortran doing the lookups, because we have to have this feature anyway there for testing, and then create minimal plumbing to communicate this to the LSP, and LSP forwarding to VSCode. We should create a branch in fortls that reuses the fortls VSCode extension, then we'll use pygls to handle the protocol, and then hook it up with LFortran.

### Testing

Once we have a minimal implementation of the previous two points, we'll start testing it with various codes. We will discover various bugs in LFortran ASR error-resiliency, so we add tests to LFortran and fix our parser and/or semantics. The goal is to rather not being able to figure out some information, but we cannot fail, no matter what code the user gives us. Our job is to mainly get the LFortran side completely robust and correct, and get some minimal LSP plumbing done to make this usable.

Once our foundation is rock solid, we will then work with the fortls author to polish, clean up and design the LSP part that will live in fortls.

**Comment by certik** [comment]
Maybe we can start testing it with valid codes, such as:
```fortran
program expr2
integer :: x
integer :: abc, abcdef
x = (2+3)*abc
print *, x
end program
```
When the cursor is right after `abc`, it should give a valid tab completion `abcdef`. The above code is valid and `lfortran --show-asr` will show ASR for it.

**Comment by Pranavchiku** [comment]
More specifically: ( TODO for other PRs )

* [x] add test to validate line column information of a variable #4845
* [ ] Introduce `--lookup-name`, `--line=xx`, `--column=xx` compiler flags
* [ ] implement these
* [ ] write a logic to search for ASR node at corresponding location  after generation of ASR.

**Comment by Pranavchiku** [comment]
I am documenting the approach that I have in mind to implement `--lookup-name`. This might be a naive implementation but can get things working.

1. Create a BaseWalkVisitor, iterate over each node, fetch its `loc`, create vector of `diag::Span` from it similar to `std::vector<diag::Span> spans = diag::Label("", {sym->base.loc}).spans;` then iterate over spans, `populate_span` and find line and column information for it. If it matches with what we have via `--line` and `--column`, perfect.

The trouble with this approach is compuatation of `populate_span` over each node.

2. Other way is to write a function that computes `loc` information from `--line` and `--column` and then we can iteate over nodes and compare `loc` directly.

We have a function inside `semantics.h` that converts `linecol_to_pos`

```cpp
// Converts (line, col) to a linear position.
uint64_t linecol_to_pos(const std::string &s, uint16_t line, uint16_t col) {
    uint64_t pos = 0;
    uint64_t l = 1;
    while (true) {
        if (l == line) break;
        if (pos >= s.size()) return 0;
        while (s[pos] != '\n' && pos < s.size()) pos++;
        l++;
        pos++;
    }
    pos += col-1;
    if (pos >= s.size()) return 0;
    return pos;
}
```

and a function inside `location.h` that converts `pos_to_linecol`.

**Comment by certik** [comment]
You should always first convert "filename + line + column" into just one location index. Only use this index (`pos`) for computation --- so just walk over every node, and:

* Check if `first<= pos` and `pos <= last`
* If so, compute `span = last - first` (just an integer)
* If `span` is less than the last stored `span`, then store this ASR node, together with its `span`

At the end you will have an ASR node with the smallest span, which is a good ASR node to return.

**Comment by Pranavchiku** [comment]
I have made progress, I am able to return `Variable` with given line and column, for ex:

```fortran
module a
    integer :: x,y,z
end module

real function f()
    use a
    f = x + y + z
end function

program main
    integer :: x, y, z
    print *, f()
end program
```

```console
% lfortran a.f90 --show-asr --lookup-name --line=11 --column=16
...
4 x
```

Returns me corresponding variable node :)

Now, I need to just mangle function return types to print it automatically.
