### ISSUE TITLE
GSoC 2022: Implementing custom WASM Backend for LFortran Roadmap

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#540]
*Original issue*: https://gitlab.com/lfortran/lfortran/-/issues/700

- [x] Initial `wasm->wat` backend (https://gitlab.com/lfortran/lfortran/-/merge_requests/1757)
- [x] Setting up testing infrastructure (https://gitlab.com/lfortran/lfortran/-/merge_requests/1760)
- [x] Enable LLVM based WASM backend in LFortran (https://gitlab.com/lfortran/lfortran/-/merge_requests/1769 , https://gitlab.com/lfortran/lfortran/-/merge_requests/1768 )
- [x] Compile (LFortran + wasm backend) to wasm
    - [x] compile essential components to wasm (https://gitlab.com/lfortran/lfortran/-/merge_requests/1796)
    - [x] support runtime library (https://github.com/lfortran/lfortran/issues/555)
- [x] Setup a demo page at [lfortran.org](https://lfortran.org/) that hosts LFortran and compiles Fortran and runs in the browser
    - [x] build a basic frontend ([repo](https://github.com/Shaikh-Ubaid/lcompilers_frontend))
    - [x] deploy to [dev.lfortran.org](https://dev.lfortran.org/) (https://github.com/lfortran/lcompilers_frontend)
- [x] Implement CI testing
    - [x] https://gitlab.com/lfortran/lfortran/-/issues/711 (https://gitlab.com/lfortran/lfortran/-/merge_requests/1794)
    - [x] https://gitlab.com/lfortran/lfortran/-/issues/712 (https://gitlab.com/lfortran/lfortran/-/merge_requests/1797, https://gitlab.com/lfortran/lfortran/-/merge_requests/1808)
    - [x] install `node`/`emscripten` at `CI` (https://github.com/lfortran/lfortran/pull/157)
- [x] Add support for 32-bit and 64-bit integer numbers and operations between them:
    - [x] support for constants/literals (https://gitlab.com/lfortran/lfortran/-/merge_requests/1789)    
    - unary operators 
        - [x] unary minus (https://gitlab.com/lfortran/lfortran/-/merge_requests/1791)
    - arithmetic operators 
        - [x] basic (Add, Sub, Mul, Div) (https://gitlab.com/lfortran/lfortran/-/merge_requests/1762)
        - [x] pow operation (for x**2) (https://github.com/lfortran/lfortran/pull/118)
        - [x] modulo operator (https://gitlab.com/lfortran/lfortran/-/merge_requests/1834)
    - [x] relational operators (https://gitlab.com/lfortran/lfortran/-/merge_requests/1823)
    - [x] logical operators (https://gitlab.com/lfortran/lfortran/-/merge_requests/1824)
- [x] Add support for 32-bit and 64-bit floating point numbers and operations between them
    - [x] support for constants/literals (https://gitlab.com/lfortran/lfortran/-/merge_requests/1792)
    - unary operators
        - [x] unary minus (https://gitlab.com/lfortran/lfortran/-/merge_requests/1792)
    - arithmetic operators
        - [x] basic (Add, Sub, Mul, Div) (https://gitlab.com/lfortran/lfortran/-/merge_requests/1792)
        - [x] pow operation (x**2.0) (https://github.com/lfortran/lfortran/pull/118)
    - [x] relational operators (https://gitlab.com/lfortran/lfortran/-/merge_requests/1823)
    - [x] modulo operator (https://gitlab.com/lfortran/lfortran/-/merge_requests/1834)
- [x] Wrap program statements (global statements) into a function (lets say `_main` or `main_`) (first commit of https://gitlab.com/lfortran/lfortran/-/merge_requests/1794)
- Add support for if-else blocks in the wasm backend
    - [x] basic support (https://gitlab.com/lfortran/lfortran/-/merge_requests/1809)
    - [x] extended support (https://gitlab.com/lfortran/lfortran/-/merge_requests/1823, https://gitlab.com/lfortran/lfortran/-/merge_requests/1824)
- [x] Add support for loops in the wasm backend
    - [x] basic support (https://gitlab.com/lfortran/lfortran/-/merge_requests/1830)
    - [x] support for cycle (https://gitlab.com/lfortran/lfortran/-/merge_requests/1830)
    - [x] support for break (https://gitlab.com/lfortran/lfortran/-/merge_requests/1830)
- [x] Add support for functions and subroutines
    - [x] basic support and function calls
    - [x] support declaring functions in any order (https://github.com/lfortran/lfortran/pull/635)   
- Miscellaneous
    - [x] support variable initialisation at declaration (https://gitlab.com/lfortran/lfortran/-/merge_requests/1834)
- [x] Add support for casting/type-conversion (https://gitlab.com/lfortran/lfortran/-/merge_requests/1822)
- [x] Add support for strings
    - [x] Basic support (https://github.com/lfortran/lfortran/pull/640) 
- [x] Add support for arrays
    - [x] Initial Support (#49 #55)
    - [x] `real` and `logical` types support (#66)
    - [x] compile-time multi-dimensional arrays (#70, #99, #109) 
- [x] Add some demo, say some image processing/mandelbrot, show the result in canvas on the demo page ([dev.lfortran.org](https://dev.lfortran.org/))

**Comment by Shaikh-Ubaid** [comment]
Associated: https://github.com/lfortran/lfortran/issues/441, https://github.com/lfortran/lfortran/issues/531, [gitlab #706](https://gitlab.com/lfortran/lfortran/-/issues/706), https://github.com/lfortran/lfortran/issues/555, https://github.com/lfortran/lfortran/issues/586, https://github.com/lfortran/lfortran/issues/594, [gitlab #711](https://gitlab.com/lfortran/lfortran/-/issues/711), [gitlab #712](https://gitlab.com/lfortran/lfortran/-/issues/712)

**Comment by Shaikh-Ubaid** [comment]
Please, could someone possibly share if this issue is safe to close?

**Comment by certik** [comment]
I think this issue is fixed! Go ahead and close it if you agree.

**Comment by Shaikh-Ubaid** [comment]
>I think this issue is fixed!

Got it. Thank you.

I am closing this issue for now as it seems to be fixed.

**Comment by Shaikh-Ubaid** [comment]
The Web front-end implemented as a part of this GSoC project is at https://github.com/lfortran/lcompilers_frontend. The report is available at https://www.ubaidshaikh.me/blogs/gsoc_13_report.

The final outcome is a live website which hosts the `LFortran` compiler (compiled to binary `wasm`). It is deployed at https://dev.lfortran.org/.
