### ISSUE TITLE
WASM: Upcoming tasks

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#586]
*Original issue*: https://gitlab.com/lfortran/lfortran/-/issues/761

From [Zulip Chat: Building LFortran inemscripten-forge](https://lfortran.zulipchat.com/#narrow/stream/197339-general/topic/Building.20LFortran.20in.20emscripten-forge), it seems we need the following support:

- [x] building to `wasm` at `CI` (Release type. If it works unexpectedly, we need to recompile in Debug mode and debug it.) (#157)
- [x] auto uploading the built `lfortran.wasm` && `lfortran.js` to https://dev.lfortran.org/ (#157)

Also, other supports needed:
- [x] support `pow` for `x**2` case [https://gitlab.com/lfortran/lfortran/-/issues/118 (merged)](https://github.com/lfortran/lfortran/pull/118)
- [x] start with sufficient memory in the generated `wasm` (more details at [comment](https://github.com/lfortran/lfortran/pull/99#issuecomment-1207330794), [comment](https://github.com/lfortran/lfortran/pull/99#issuecomment-1207342062)) [https://gitlab.com/lfortran/lfortran/-/issues/126 (merged)](https://github.com/lfortran/lfortran/pull/126).
- [x] passing array data from/between `wasm` and `JavaScript`
- [x] generate the WASM "imports" based on `bind(c)` interfaces (https://gitlab.com/lfortran/lfortran/-/issues/771) (#588 
- [x] drawing/visualizing the image (generated by `wasm`) on `canvas`

**Comment by Shaikh-Ubaid** [comment]
I removed `runtime` library and `strings` from the above description.
- `Runtime` library already has a dedicated issue at https://github.com/lfortran/lfortran/issues/555
- `strings` are already noted at https://github.com/lfortran/lfortran/issues/540
    - We can/might create a separate/dedicated issue for `strings` later

**Comment by Shaikh-Ubaid** [comment]
Please possibly review. It seems safe to close this issue.

**Comment by certik** [comment]
I think everything is fixed here, thanks @Shaikh-Ubaid.

The auto uploading of `lfortran.wasm` still needs some improvements, but we have a dedicated issue for that: https://github.com/lfortran/lcompilers_frontend/issues/12, everything else I think is done.
